
// This file has been generated by the GUI designer. Do not modify.
namespace Mundus.Views.Windows
{
	public partial class NewGameWindow
	{
		private global::Gtk.Table tbUI;

		private global::Gtk.Button btnBack;

		private global::Gtk.Button btnGenerate;

		private global::Gtk.HSeparator hSeparator;

		private global::Gtk.Label lblBlank1;

		private global::Gtk.Label lblBlank2;

		private global::Gtk.Label lblBlank3;

		private global::Gtk.Label lblBlank4;

		private global::Gtk.Label lblBlank5;

		private global::Gtk.Label lblDifficulty;

		private global::Gtk.Label lblGameMode;

		private global::Gtk.Label lblMapSize;

		private global::Gtk.Label lblScreenInvSize;

		private global::Gtk.Label lblTitle;

		private global::Gtk.RadioButton rbCreative;

		private global::Gtk.RadioButton rbEasy;

		private global::Gtk.RadioButton rbHard;

		private global::Gtk.RadioButton rbInsane;

		private global::Gtk.RadioButton rbLarge;

		private global::Gtk.RadioButton rbMedium;

		private global::Gtk.RadioButton rbMLarge;

		private global::Gtk.RadioButton rbMMedium;

		private global::Gtk.RadioButton rbMSmall;

		private global::Gtk.RadioButton rbNormal;

		private global::Gtk.RadioButton rbPeaceful;

		private global::Gtk.RadioButton rbSmall;

		private global::Gtk.RadioButton rbSurvival;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Mundus.Views.Windows.NewGameWindow
			this.Name = "Mundus.Views.Windows.NewGameWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Create a New Game");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Mundus.Views.Windows.NewGameWindow.Gtk.Container+ContainerChild
			this.tbUI = new global::Gtk.Table(((uint)(6)), ((uint)(8)), false);
			this.tbUI.Name = "tbUI";
			this.tbUI.RowSpacing = ((uint)(3));
			this.tbUI.ColumnSpacing = ((uint)(3));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnBack = new global::Gtk.Button();
			this.btnBack.WidthRequest = 50;
			this.btnBack.HeightRequest = 50;
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.BorderWidth = ((uint)(3));
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString("Back");
			this.tbUI.Add(this.btnBack);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnBack]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnGenerate = new global::Gtk.Button();
			this.btnGenerate.WidthRequest = 90;
			this.btnGenerate.HeightRequest = 50;
			this.btnGenerate.CanFocus = true;
			this.btnGenerate.Name = "btnGenerate";
			this.btnGenerate.UseUnderline = true;
			this.btnGenerate.BorderWidth = ((uint)(3));
			this.btnGenerate.Label = global::Mono.Unix.Catalog.GetString("Generate");
			this.tbUI.Add(this.btnGenerate);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnGenerate]));
			w2.LeftAttach = ((uint)(6));
			w2.RightAttach = ((uint)(7));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.hSeparator = new global::Gtk.HSeparator();
			this.hSeparator.HeightRequest = 5;
			this.hSeparator.Name = "hSeparator";
			this.tbUI.Add(this.hSeparator);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tbUI[this.hSeparator]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(7));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank1 = new global::Gtk.Label();
			this.lblBlank1.WidthRequest = 90;
			this.lblBlank1.HeightRequest = 50;
			this.lblBlank1.Name = "lblBlank1";
			this.tbUI.Add(this.lblBlank1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank1]));
			w4.LeftAttach = ((uint)(2));
			w4.RightAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank2 = new global::Gtk.Label();
			this.lblBlank2.WidthRequest = 50;
			this.lblBlank2.Name = "lblBlank2";
			this.tbUI.Add(this.lblBlank2);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank2]));
			w5.LeftAttach = ((uint)(4));
			w5.RightAttach = ((uint)(5));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank3 = new global::Gtk.Label();
			this.lblBlank3.WidthRequest = 50;
			this.lblBlank3.Name = "lblBlank3";
			this.tbUI.Add(this.lblBlank3);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank3]));
			w6.LeftAttach = ((uint)(5));
			w6.RightAttach = ((uint)(6));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank4 = new global::Gtk.Label();
			this.lblBlank4.WidthRequest = 5;
			this.lblBlank4.HeightRequest = 50;
			this.lblBlank4.Name = "lblBlank4";
			this.tbUI.Add(this.lblBlank4);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank4]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.LeftAttach = ((uint)(7));
			w7.RightAttach = ((uint)(8));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank5 = new global::Gtk.Label();
			this.lblBlank5.WidthRequest = 5;
			this.lblBlank5.HeightRequest = 50;
			this.lblBlank5.Name = "lblBlank5";
			this.tbUI.Add(this.lblBlank5);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank5]));
			w8.TopAttach = ((uint)(4));
			w8.BottomAttach = ((uint)(5));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblDifficulty = new global::Gtk.Label();
			this.lblDifficulty.WidthRequest = 90;
			this.lblDifficulty.HeightRequest = 50;
			this.lblDifficulty.Name = "lblDifficulty";
			this.lblDifficulty.LabelProp = global::Mono.Unix.Catalog.GetString("Difficulty");
			this.tbUI.Add(this.lblDifficulty);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblDifficulty]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblGameMode = new global::Gtk.Label();
			this.lblGameMode.WidthRequest = 90;
			this.lblGameMode.HeightRequest = 50;
			this.lblGameMode.Name = "lblGameMode";
			this.lblGameMode.LabelProp = global::Mono.Unix.Catalog.GetString("Game Mode:");
			this.tbUI.Add(this.lblGameMode);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblGameMode]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblMapSize = new global::Gtk.Label();
			this.lblMapSize.WidthRequest = 90;
			this.lblMapSize.HeightRequest = 50;
			this.lblMapSize.Name = "lblMapSize";
			this.lblMapSize.LabelProp = global::Mono.Unix.Catalog.GetString("Map size");
			this.tbUI.Add(this.lblMapSize);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblMapSize]));
			w11.TopAttach = ((uint)(5));
			w11.BottomAttach = ((uint)(6));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblScreenInvSize = new global::Gtk.Label();
			this.lblScreenInvSize.WidthRequest = 90;
			this.lblScreenInvSize.HeightRequest = 50;
			this.lblScreenInvSize.Name = "lblScreenInvSize";
			this.lblScreenInvSize.LabelProp = global::Mono.Unix.Catalog.GetString("Screen & Inventory size");
			this.lblScreenInvSize.Wrap = true;
			this.lblScreenInvSize.Justify = ((global::Gtk.Justification)(2));
			this.tbUI.Add(this.lblScreenInvSize);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblScreenInvSize]));
			w12.TopAttach = ((uint)(4));
			w12.BottomAttach = ((uint)(5));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblTitle = new global::Gtk.Label();
			this.lblTitle.WidthRequest = 180;
			this.lblTitle.HeightRequest = 50;
			this.lblTitle.Name = "lblTitle";
			this.lblTitle.LabelProp = global::Mono.Unix.Catalog.GetString("New Game (replace with picture)");
			this.lblTitle.Wrap = true;
			this.lblTitle.Justify = ((global::Gtk.Justification)(2));
			this.tbUI.Add(this.lblTitle);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblTitle]));
			w13.LeftAttach = ((uint)(3));
			w13.RightAttach = ((uint)(5));
			w13.XOptions = ((global::Gtk.AttachOptions)(0));
			w13.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbCreative = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Creative"));
			this.rbCreative.WidthRequest = 90;
			this.rbCreative.CanFocus = true;
			this.rbCreative.Name = "rbCreative";
			this.rbCreative.DrawIndicator = true;
			this.rbCreative.UseUnderline = true;
			this.rbCreative.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.tbUI.Add(this.rbCreative);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbCreative]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.LeftAttach = ((uint)(3));
			w14.RightAttach = ((uint)(4));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbEasy = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Easy"));
			this.rbEasy.WidthRequest = 90;
			this.rbEasy.CanFocus = true;
			this.rbEasy.Name = "rbEasy";
			this.rbEasy.DrawIndicator = true;
			this.rbEasy.UseUnderline = true;
			this.rbEasy.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.tbUI.Add(this.rbEasy);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbEasy]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.LeftAttach = ((uint)(3));
			w15.RightAttach = ((uint)(4));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbHard = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Hard"));
			this.rbHard.WidthRequest = 90;
			this.rbHard.CanFocus = true;
			this.rbHard.Name = "rbHard";
			this.rbHard.DrawIndicator = true;
			this.rbHard.UseUnderline = true;
			this.rbHard.Group = this.rbEasy.Group;
			this.tbUI.Add(this.rbHard);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbHard]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.LeftAttach = ((uint)(5));
			w16.RightAttach = ((uint)(6));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbInsane = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Insane"));
			this.rbInsane.WidthRequest = 90;
			this.rbInsane.CanFocus = true;
			this.rbInsane.Name = "rbInsane";
			this.rbInsane.DrawIndicator = true;
			this.rbInsane.UseUnderline = true;
			this.rbInsane.Group = this.rbEasy.Group;
			this.tbUI.Add(this.rbInsane);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbInsane]));
			w17.TopAttach = ((uint)(3));
			w17.BottomAttach = ((uint)(4));
			w17.LeftAttach = ((uint)(6));
			w17.RightAttach = ((uint)(7));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbLarge = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Large"));
			this.rbLarge.WidthRequest = 90;
			this.rbLarge.CanFocus = true;
			this.rbLarge.Name = "rbLarge";
			this.rbLarge.DrawIndicator = true;
			this.rbLarge.UseUnderline = true;
			this.rbLarge.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.tbUI.Add(this.rbLarge);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbLarge]));
			w18.TopAttach = ((uint)(4));
			w18.BottomAttach = ((uint)(5));
			w18.LeftAttach = ((uint)(4));
			w18.RightAttach = ((uint)(5));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbMedium = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Medium"));
			this.rbMedium.WidthRequest = 90;
			this.rbMedium.CanFocus = true;
			this.rbMedium.Name = "rbMedium";
			this.rbMedium.DrawIndicator = true;
			this.rbMedium.UseUnderline = true;
			this.rbMedium.Group = this.rbLarge.Group;
			this.tbUI.Add(this.rbMedium);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbMedium]));
			w19.TopAttach = ((uint)(4));
			w19.BottomAttach = ((uint)(5));
			w19.LeftAttach = ((uint)(3));
			w19.RightAttach = ((uint)(4));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbMLarge = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Large"));
			this.rbMLarge.CanFocus = true;
			this.rbMLarge.Name = "rbMLarge";
			this.rbMLarge.DrawIndicator = true;
			this.rbMLarge.UseUnderline = true;
			this.rbMLarge.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.tbUI.Add(this.rbMLarge);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbMLarge]));
			w20.TopAttach = ((uint)(5));
			w20.BottomAttach = ((uint)(6));
			w20.LeftAttach = ((uint)(4));
			w20.RightAttach = ((uint)(5));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbMMedium = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Medium"));
			this.rbMMedium.WidthRequest = 90;
			this.rbMMedium.CanFocus = true;
			this.rbMMedium.Name = "rbMMedium";
			this.rbMMedium.DrawIndicator = true;
			this.rbMMedium.UseUnderline = true;
			this.rbMMedium.Group = this.rbMLarge.Group;
			this.tbUI.Add(this.rbMMedium);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbMMedium]));
			w21.TopAttach = ((uint)(5));
			w21.BottomAttach = ((uint)(6));
			w21.LeftAttach = ((uint)(3));
			w21.RightAttach = ((uint)(4));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbMSmall = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Small"));
			this.rbMSmall.WidthRequest = 90;
			this.rbMSmall.CanFocus = true;
			this.rbMSmall.Name = "rbMSmall";
			this.rbMSmall.DrawIndicator = true;
			this.rbMSmall.UseUnderline = true;
			this.rbMSmall.Group = this.rbMLarge.Group;
			this.tbUI.Add(this.rbMSmall);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbMSmall]));
			w22.TopAttach = ((uint)(5));
			w22.BottomAttach = ((uint)(6));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbNormal = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Normal"));
			this.rbNormal.WidthRequest = 90;
			this.rbNormal.CanFocus = true;
			this.rbNormal.Name = "rbNormal";
			this.rbNormal.DrawIndicator = true;
			this.rbNormal.UseUnderline = true;
			this.rbNormal.Group = this.rbEasy.Group;
			this.tbUI.Add(this.rbNormal);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbNormal]));
			w23.TopAttach = ((uint)(3));
			w23.BottomAttach = ((uint)(4));
			w23.LeftAttach = ((uint)(4));
			w23.RightAttach = ((uint)(5));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbPeaceful = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Peaceful"));
			this.rbPeaceful.WidthRequest = 90;
			this.rbPeaceful.CanFocus = true;
			this.rbPeaceful.Name = "rbPeaceful";
			this.rbPeaceful.DrawIndicator = true;
			this.rbPeaceful.UseUnderline = true;
			this.rbPeaceful.Group = this.rbEasy.Group;
			this.tbUI.Add(this.rbPeaceful);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbPeaceful]));
			w24.TopAttach = ((uint)(3));
			w24.BottomAttach = ((uint)(4));
			w24.LeftAttach = ((uint)(2));
			w24.RightAttach = ((uint)(3));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbSmall = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Small"));
			this.rbSmall.WidthRequest = 90;
			this.rbSmall.CanFocus = true;
			this.rbSmall.Name = "rbSmall";
			this.rbSmall.DrawIndicator = true;
			this.rbSmall.UseUnderline = true;
			this.rbSmall.Group = this.rbLarge.Group;
			this.tbUI.Add(this.rbSmall);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbSmall]));
			w25.TopAttach = ((uint)(4));
			w25.BottomAttach = ((uint)(5));
			w25.LeftAttach = ((uint)(2));
			w25.RightAttach = ((uint)(3));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.rbSurvival = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Survival"));
			this.rbSurvival.WidthRequest = 90;
			this.rbSurvival.CanFocus = true;
			this.rbSurvival.Name = "rbSurvival";
			this.rbSurvival.DrawIndicator = true;
			this.rbSurvival.UseUnderline = true;
			this.rbSurvival.Group = this.rbCreative.Group;
			this.tbUI.Add(this.rbSurvival);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.tbUI[this.rbSurvival]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			w26.LeftAttach = ((uint)(2));
			w26.RightAttach = ((uint)(3));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.tbUI);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 581;
			this.DefaultHeight = 275;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.rbSmall.Toggled += new global::System.EventHandler(this.OnRbSmallToggled);
			this.rbMedium.Toggled += new global::System.EventHandler(this.OnRbMediumToggled);
			this.rbLarge.Toggled += new global::System.EventHandler(this.OnRbLargeToggled);
			this.rbCreative.Toggled += new global::System.EventHandler(this.OnRbCreativeToggled);
			this.btnGenerate.Clicked += new global::System.EventHandler(this.OnBtnGenerateClicked);
			this.btnBack.Clicked += new global::System.EventHandler(this.OnBtnBackClicked);
		}
	}
}
