
// This file has been generated by the GUI designer. Do not modify.
namespace Mundus.Views.Windows
{
	public partial class SmallGameWindow
	{
		private global::Gtk.Table tbUI;

		private global::Gtk.Button bntI7;

		private global::Gtk.Button btnGM1;

		private global::Gtk.Button btnGM2;

		private global::Gtk.Button btnGM3;

		private global::Gtk.Button btnH1;

		private global::Gtk.Button btnH2;

		private global::Gtk.Button btnH3;

		private global::Gtk.Button btnH4;

		private global::Gtk.Button btnH5;

		private global::Gtk.Button btnI1;

		private global::Gtk.Button btnI10;

		private global::Gtk.Button btnI11;

		private global::Gtk.Button btnI12;

		private global::Gtk.Button btnI13;

		private global::Gtk.Button btnI14;

		private global::Gtk.Button btnI15;

		private global::Gtk.Button btnI16;

		private global::Gtk.Button btnI17;

		private global::Gtk.Button btnI18;

		private global::Gtk.Button btnI19;

		private global::Gtk.Button btnI2;

		private global::Gtk.Button btnI20;

		private global::Gtk.Button btnI21;

		private global::Gtk.Button btnI22;

		private global::Gtk.Button btnI23;

		private global::Gtk.Button btnI24;

		private global::Gtk.Button btnI25;

		private global::Gtk.Button btnI3;

		private global::Gtk.Button btnI4;

		private global::Gtk.Button btnI5;

		private global::Gtk.Button btnI6;

		private global::Gtk.Button btnI8;

		private global::Gtk.Button btnI9;

		private global::Gtk.Button btnIM1;

		private global::Gtk.Button btnIM2;

		private global::Gtk.Button btnIM3;

		private global::Gtk.Button btnInv;

		private global::Gtk.Button btnMap;

		private global::Gtk.Button btnMusic;

		private global::Gtk.Button btnP1;

		private global::Gtk.Button btnP10;

		private global::Gtk.Button btnP11;

		private global::Gtk.Button btnP13;

		private global::Gtk.Button btnP14;

		private global::Gtk.Button btnP15;

		private global::Gtk.Button btnP16;

		private global::Gtk.Button btnP17;

		private global::Gtk.Button btnP18;

		private global::Gtk.Button btnP19;

		private global::Gtk.Button btnP2;

		private global::Gtk.Button btnP20;

		private global::Gtk.Button btnP21;

		private global::Gtk.Button btnP22;

		private global::Gtk.Button btnP23;

		private global::Gtk.Button btnP24;

		private global::Gtk.Button btnP25;

		private global::Gtk.Button btnP3;

		private global::Gtk.Button btnP4;

		private global::Gtk.Button btnP5;

		private global::Gtk.Button btnP6;

		private global::Gtk.Button btnP7;

		private global::Gtk.Button btnP8;

		private global::Gtk.Button btnP9;

		private global::Gtk.Button btnPause;

		private global::Gtk.Button button12;

		private global::Gtk.Image imgG1;

		private global::Gtk.Image imgG10;

		private global::Gtk.Image imgG11;

		private global::Gtk.Image imgG12;

		private global::Gtk.Image imgG13;

		private global::Gtk.Image imgG14;

		private global::Gtk.Image imgG15;

		private global::Gtk.Image imgG16;

		private global::Gtk.Image imgG17;

		private global::Gtk.Image imgG18;

		private global::Gtk.Image imgG19;

		private global::Gtk.Image imgG2;

		private global::Gtk.Image imgG20;

		private global::Gtk.Image imgG21;

		private global::Gtk.Image imgG22;

		private global::Gtk.Image imgG23;

		private global::Gtk.Image imgG24;

		private global::Gtk.Image imgG25;

		private global::Gtk.Image imgG3;

		private global::Gtk.Image imgG4;

		private global::Gtk.Image imgG5;

		private global::Gtk.Image imgG6;

		private global::Gtk.Image imgG7;

		private global::Gtk.Image imgG8;

		private global::Gtk.Image imgG9;

		private global::Gtk.Image imgI1;

		private global::Gtk.Image imgI10;

		private global::Gtk.Image imgI11;

		private global::Gtk.Image imgI12;

		private global::Gtk.Image imgI13;

		private global::Gtk.Image imgI14;

		private global::Gtk.Image imgI15;

		private global::Gtk.Image imgI16;

		private global::Gtk.Image imgI17;

		private global::Gtk.Image imgI18;

		private global::Gtk.Image imgI19;

		private global::Gtk.Image imgI2;

		private global::Gtk.Image imgI20;

		private global::Gtk.Image imgI21;

		private global::Gtk.Image imgI22;

		private global::Gtk.Image imgI23;

		private global::Gtk.Image imgI24;

		private global::Gtk.Image imgI25;

		private global::Gtk.Image imgI3;

		private global::Gtk.Image imgI4;

		private global::Gtk.Image imgI5;

		private global::Gtk.Image imgI6;

		private global::Gtk.Image imgI7;

		private global::Gtk.Image imgI8;

		private global::Gtk.Image imgI9;

		private global::Gtk.Image imgS1;

		private global::Gtk.Image imgS10;

		private global::Gtk.Image imgS2;

		private global::Gtk.Image imgS3;

		private global::Gtk.Image imgS4;

		private global::Gtk.Image imgS5;

		private global::Gtk.Image imgS6;

		private global::Gtk.Image imgS7;

		private global::Gtk.Image imgS8;

		private global::Gtk.Image imgS9;

		private global::Gtk.Label lblBlank1;

		private global::Gtk.Label lblBlank2;

		private global::Gtk.Label lblBlank3;

		private global::Gtk.Label lblBlank4;

		private global::Gtk.Label lblBlank5;

		private global::Gtk.Label lblBlank6;

		private global::Gtk.Label lblBlank7;

		private global::Gtk.Label lblBlank8;

		private global::Gtk.Label lblBlank9;

		private global::Gtk.Label lblLog1;

		private global::Gtk.Label lblLog2;

		private global::Gtk.Label lblLog3;

		private global::Gtk.Label lblLog4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Mundus.Views.Windows.SmallGameWindow
			this.Name = "Mundus.Views.Windows.SmallGameWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Mundus (Small Window)");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Mundus.Views.Windows.SmallGameWindow.Gtk.Container+ContainerChild
			this.tbUI = new global::Gtk.Table(((uint)(17)), ((uint)(21)), false);
			this.tbUI.Name = "tbUI";
			// Container child tbUI.Gtk.Table+TableChild
			this.bntI7 = new global::Gtk.Button();
			this.bntI7.WidthRequest = 50;
			this.bntI7.HeightRequest = 50;
			this.bntI7.CanFocus = true;
			this.bntI7.Name = "bntI7";
			this.bntI7.UseUnderline = true;
			this.bntI7.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w1 = new global::Gtk.Image();
			this.bntI7.Image = w1;
			this.tbUI.Add(this.bntI7);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tbUI[this.bntI7]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.LeftAttach = ((uint)(16));
			w2.RightAttach = ((uint)(17));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnGM1 = new global::Gtk.Button();
			this.btnGM1.WidthRequest = 50;
			this.btnGM1.HeightRequest = 50;
			this.btnGM1.CanFocus = true;
			this.btnGM1.Name = "btnGM1";
			this.btnGM1.UseUnderline = true;
			this.btnGM1.Label = global::Mono.Unix.Catalog.GetString("1:1");
			this.tbUI.Add(this.btnGM1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnGM1]));
			w3.TopAttach = ((uint)(7));
			w3.BottomAttach = ((uint)(8));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnGM2 = new global::Gtk.Button();
			this.btnGM2.WidthRequest = 50;
			this.btnGM2.HeightRequest = 50;
			this.btnGM2.CanFocus = true;
			this.btnGM2.Name = "btnGM2";
			this.btnGM2.UseUnderline = true;
			this.btnGM2.Label = global::Mono.Unix.Catalog.GetString("1:5");
			this.tbUI.Add(this.btnGM2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnGM2]));
			w4.TopAttach = ((uint)(7));
			w4.BottomAttach = ((uint)(8));
			w4.LeftAttach = ((uint)(3));
			w4.RightAttach = ((uint)(4));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnGM3 = new global::Gtk.Button();
			this.btnGM3.WidthRequest = 50;
			this.btnGM3.HeightRequest = 50;
			this.btnGM3.CanFocus = true;
			this.btnGM3.Name = "btnGM3";
			this.btnGM3.UseUnderline = true;
			this.btnGM3.Label = global::Mono.Unix.Catalog.GetString("1:10");
			this.tbUI.Add(this.btnGM3);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnGM3]));
			w5.TopAttach = ((uint)(7));
			w5.BottomAttach = ((uint)(8));
			w5.LeftAttach = ((uint)(5));
			w5.RightAttach = ((uint)(6));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnH1 = new global::Gtk.Button();
			this.btnH1.WidthRequest = 50;
			this.btnH1.HeightRequest = 50;
			this.btnH1.CanFocus = true;
			this.btnH1.Name = "btnH1";
			this.btnH1.UseUnderline = true;
			this.btnH1.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w6 = new global::Gtk.Image();
			this.btnH1.Image = w6;
			this.tbUI.Add(this.btnH1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnH1]));
			w7.TopAttach = ((uint)(10));
			w7.BottomAttach = ((uint)(11));
			w7.LeftAttach = ((uint)(8));
			w7.RightAttach = ((uint)(9));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnH2 = new global::Gtk.Button();
			this.btnH2.WidthRequest = 50;
			this.btnH2.HeightRequest = 50;
			this.btnH2.CanFocus = true;
			this.btnH2.Name = "btnH2";
			this.btnH2.UseUnderline = true;
			this.btnH2.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w8 = new global::Gtk.Image();
			this.btnH2.Image = w8;
			this.tbUI.Add(this.btnH2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnH2]));
			w9.TopAttach = ((uint)(10));
			w9.BottomAttach = ((uint)(11));
			w9.LeftAttach = ((uint)(9));
			w9.RightAttach = ((uint)(10));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnH3 = new global::Gtk.Button();
			this.btnH3.WidthRequest = 50;
			this.btnH3.HeightRequest = 50;
			this.btnH3.CanFocus = true;
			this.btnH3.Name = "btnH3";
			this.btnH3.UseUnderline = true;
			this.btnH3.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w10 = new global::Gtk.Image();
			this.btnH3.Image = w10;
			this.tbUI.Add(this.btnH3);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnH3]));
			w11.TopAttach = ((uint)(10));
			w11.BottomAttach = ((uint)(11));
			w11.LeftAttach = ((uint)(10));
			w11.RightAttach = ((uint)(11));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnH4 = new global::Gtk.Button();
			this.btnH4.WidthRequest = 50;
			this.btnH4.HeightRequest = 50;
			this.btnH4.CanFocus = true;
			this.btnH4.Name = "btnH4";
			this.btnH4.UseUnderline = true;
			this.btnH4.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w12 = new global::Gtk.Image();
			this.btnH4.Image = w12;
			this.tbUI.Add(this.btnH4);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnH4]));
			w13.TopAttach = ((uint)(10));
			w13.BottomAttach = ((uint)(11));
			w13.LeftAttach = ((uint)(11));
			w13.RightAttach = ((uint)(12));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnH5 = new global::Gtk.Button();
			this.btnH5.WidthRequest = 50;
			this.btnH5.HeightRequest = 50;
			this.btnH5.CanFocus = true;
			this.btnH5.Name = "btnH5";
			this.btnH5.UseUnderline = true;
			this.btnH5.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w14 = new global::Gtk.Image();
			this.btnH5.Image = w14;
			this.tbUI.Add(this.btnH5);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnH5]));
			w15.TopAttach = ((uint)(10));
			w15.BottomAttach = ((uint)(11));
			w15.LeftAttach = ((uint)(12));
			w15.RightAttach = ((uint)(13));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI1 = new global::Gtk.Button();
			this.btnI1.WidthRequest = 50;
			this.btnI1.HeightRequest = 50;
			this.btnI1.CanFocus = true;
			this.btnI1.Name = "btnI1";
			this.btnI1.UseUnderline = true;
			this.btnI1.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w16 = new global::Gtk.Image();
			this.btnI1.Image = w16;
			this.tbUI.Add(this.btnI1);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI1]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.LeftAttach = ((uint)(15));
			w17.RightAttach = ((uint)(16));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI10 = new global::Gtk.Button();
			this.btnI10.WidthRequest = 50;
			this.btnI10.HeightRequest = 50;
			this.btnI10.CanFocus = true;
			this.btnI10.Name = "btnI10";
			this.btnI10.UseUnderline = true;
			this.btnI10.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w18 = new global::Gtk.Image();
			this.btnI10.Image = w18;
			this.tbUI.Add(this.btnI10);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI10]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.LeftAttach = ((uint)(19));
			w19.RightAttach = ((uint)(20));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI11 = new global::Gtk.Button();
			this.btnI11.WidthRequest = 50;
			this.btnI11.HeightRequest = 50;
			this.btnI11.CanFocus = true;
			this.btnI11.Name = "btnI11";
			this.btnI11.UseUnderline = true;
			this.btnI11.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w20 = new global::Gtk.Image();
			this.btnI11.Image = w20;
			this.tbUI.Add(this.btnI11);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI11]));
			w21.TopAttach = ((uint)(3));
			w21.BottomAttach = ((uint)(4));
			w21.LeftAttach = ((uint)(15));
			w21.RightAttach = ((uint)(16));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI12 = new global::Gtk.Button();
			this.btnI12.WidthRequest = 50;
			this.btnI12.HeightRequest = 50;
			this.btnI12.CanFocus = true;
			this.btnI12.Name = "btnI12";
			this.btnI12.UseUnderline = true;
			this.btnI12.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w22 = new global::Gtk.Image();
			this.btnI12.Image = w22;
			this.tbUI.Add(this.btnI12);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI12]));
			w23.TopAttach = ((uint)(3));
			w23.BottomAttach = ((uint)(4));
			w23.LeftAttach = ((uint)(16));
			w23.RightAttach = ((uint)(17));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI13 = new global::Gtk.Button();
			this.btnI13.WidthRequest = 50;
			this.btnI13.HeightRequest = 50;
			this.btnI13.CanFocus = true;
			this.btnI13.Name = "btnI13";
			this.btnI13.UseUnderline = true;
			this.btnI13.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w24 = new global::Gtk.Image();
			this.btnI13.Image = w24;
			this.tbUI.Add(this.btnI13);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI13]));
			w25.TopAttach = ((uint)(3));
			w25.BottomAttach = ((uint)(4));
			w25.LeftAttach = ((uint)(17));
			w25.RightAttach = ((uint)(18));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI14 = new global::Gtk.Button();
			this.btnI14.WidthRequest = 50;
			this.btnI14.HeightRequest = 50;
			this.btnI14.CanFocus = true;
			this.btnI14.Name = "btnI14";
			this.btnI14.UseUnderline = true;
			this.btnI14.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w26 = new global::Gtk.Image();
			this.btnI14.Image = w26;
			this.tbUI.Add(this.btnI14);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI14]));
			w27.TopAttach = ((uint)(3));
			w27.BottomAttach = ((uint)(4));
			w27.LeftAttach = ((uint)(18));
			w27.RightAttach = ((uint)(19));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI15 = new global::Gtk.Button();
			this.btnI15.WidthRequest = 50;
			this.btnI15.HeightRequest = 50;
			this.btnI15.CanFocus = true;
			this.btnI15.Name = "btnI15";
			this.btnI15.UseUnderline = true;
			this.btnI15.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w28 = new global::Gtk.Image();
			this.btnI15.Image = w28;
			this.tbUI.Add(this.btnI15);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI15]));
			w29.TopAttach = ((uint)(3));
			w29.BottomAttach = ((uint)(4));
			w29.LeftAttach = ((uint)(19));
			w29.RightAttach = ((uint)(20));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI16 = new global::Gtk.Button();
			this.btnI16.WidthRequest = 50;
			this.btnI16.HeightRequest = 50;
			this.btnI16.CanFocus = true;
			this.btnI16.Name = "btnI16";
			this.btnI16.UseUnderline = true;
			this.btnI16.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w30 = new global::Gtk.Image();
			this.btnI16.Image = w30;
			this.tbUI.Add(this.btnI16);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI16]));
			w31.TopAttach = ((uint)(4));
			w31.BottomAttach = ((uint)(5));
			w31.LeftAttach = ((uint)(15));
			w31.RightAttach = ((uint)(16));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI17 = new global::Gtk.Button();
			this.btnI17.WidthRequest = 50;
			this.btnI17.HeightRequest = 50;
			this.btnI17.CanFocus = true;
			this.btnI17.Name = "btnI17";
			this.btnI17.UseUnderline = true;
			this.btnI17.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w32 = new global::Gtk.Image();
			this.btnI17.Image = w32;
			this.tbUI.Add(this.btnI17);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI17]));
			w33.TopAttach = ((uint)(4));
			w33.BottomAttach = ((uint)(5));
			w33.LeftAttach = ((uint)(16));
			w33.RightAttach = ((uint)(17));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI18 = new global::Gtk.Button();
			this.btnI18.WidthRequest = 50;
			this.btnI18.HeightRequest = 50;
			this.btnI18.CanFocus = true;
			this.btnI18.Name = "btnI18";
			this.btnI18.UseUnderline = true;
			this.btnI18.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w34 = new global::Gtk.Image();
			this.btnI18.Image = w34;
			this.tbUI.Add(this.btnI18);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI18]));
			w35.TopAttach = ((uint)(4));
			w35.BottomAttach = ((uint)(5));
			w35.LeftAttach = ((uint)(17));
			w35.RightAttach = ((uint)(18));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI19 = new global::Gtk.Button();
			this.btnI19.WidthRequest = 50;
			this.btnI19.HeightRequest = 50;
			this.btnI19.CanFocus = true;
			this.btnI19.Name = "btnI19";
			this.btnI19.UseUnderline = true;
			this.btnI19.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w36 = new global::Gtk.Image();
			this.btnI19.Image = w36;
			this.tbUI.Add(this.btnI19);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI19]));
			w37.TopAttach = ((uint)(4));
			w37.BottomAttach = ((uint)(5));
			w37.LeftAttach = ((uint)(18));
			w37.RightAttach = ((uint)(19));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI2 = new global::Gtk.Button();
			this.btnI2.WidthRequest = 50;
			this.btnI2.HeightRequest = 50;
			this.btnI2.CanFocus = true;
			this.btnI2.Name = "btnI2";
			this.btnI2.UseUnderline = true;
			this.btnI2.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w38 = new global::Gtk.Image();
			this.btnI2.Image = w38;
			this.tbUI.Add(this.btnI2);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI2]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(2));
			w39.LeftAttach = ((uint)(16));
			w39.RightAttach = ((uint)(17));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI20 = new global::Gtk.Button();
			this.btnI20.WidthRequest = 50;
			this.btnI20.HeightRequest = 50;
			this.btnI20.CanFocus = true;
			this.btnI20.Name = "btnI20";
			this.btnI20.UseUnderline = true;
			this.btnI20.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w40 = new global::Gtk.Image();
			this.btnI20.Image = w40;
			this.tbUI.Add(this.btnI20);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI20]));
			w41.TopAttach = ((uint)(4));
			w41.BottomAttach = ((uint)(5));
			w41.LeftAttach = ((uint)(19));
			w41.RightAttach = ((uint)(20));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI21 = new global::Gtk.Button();
			this.btnI21.WidthRequest = 50;
			this.btnI21.HeightRequest = 50;
			this.btnI21.CanFocus = true;
			this.btnI21.Name = "btnI21";
			this.btnI21.UseUnderline = true;
			this.btnI21.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w42 = new global::Gtk.Image();
			this.btnI21.Image = w42;
			this.tbUI.Add(this.btnI21);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI21]));
			w43.TopAttach = ((uint)(5));
			w43.BottomAttach = ((uint)(6));
			w43.LeftAttach = ((uint)(15));
			w43.RightAttach = ((uint)(16));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI22 = new global::Gtk.Button();
			this.btnI22.WidthRequest = 50;
			this.btnI22.HeightRequest = 50;
			this.btnI22.CanFocus = true;
			this.btnI22.Name = "btnI22";
			this.btnI22.UseUnderline = true;
			this.btnI22.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w44 = new global::Gtk.Image();
			this.btnI22.Image = w44;
			this.tbUI.Add(this.btnI22);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI22]));
			w45.TopAttach = ((uint)(5));
			w45.BottomAttach = ((uint)(6));
			w45.LeftAttach = ((uint)(16));
			w45.RightAttach = ((uint)(17));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI23 = new global::Gtk.Button();
			this.btnI23.WidthRequest = 50;
			this.btnI23.HeightRequest = 50;
			this.btnI23.CanFocus = true;
			this.btnI23.Name = "btnI23";
			this.btnI23.UseUnderline = true;
			this.btnI23.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w46 = new global::Gtk.Image();
			this.btnI23.Image = w46;
			this.tbUI.Add(this.btnI23);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI23]));
			w47.TopAttach = ((uint)(5));
			w47.BottomAttach = ((uint)(6));
			w47.LeftAttach = ((uint)(17));
			w47.RightAttach = ((uint)(18));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI24 = new global::Gtk.Button();
			this.btnI24.WidthRequest = 50;
			this.btnI24.HeightRequest = 50;
			this.btnI24.CanFocus = true;
			this.btnI24.Name = "btnI24";
			this.btnI24.UseUnderline = true;
			this.btnI24.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w48 = new global::Gtk.Image();
			this.btnI24.Image = w48;
			this.tbUI.Add(this.btnI24);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI24]));
			w49.TopAttach = ((uint)(5));
			w49.BottomAttach = ((uint)(6));
			w49.LeftAttach = ((uint)(18));
			w49.RightAttach = ((uint)(19));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI25 = new global::Gtk.Button();
			this.btnI25.WidthRequest = 50;
			this.btnI25.HeightRequest = 50;
			this.btnI25.CanFocus = true;
			this.btnI25.Name = "btnI25";
			this.btnI25.UseUnderline = true;
			this.btnI25.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w50 = new global::Gtk.Image();
			this.btnI25.Image = w50;
			this.tbUI.Add(this.btnI25);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI25]));
			w51.TopAttach = ((uint)(5));
			w51.BottomAttach = ((uint)(6));
			w51.LeftAttach = ((uint)(19));
			w51.RightAttach = ((uint)(20));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI3 = new global::Gtk.Button();
			this.btnI3.WidthRequest = 50;
			this.btnI3.HeightRequest = 50;
			this.btnI3.CanFocus = true;
			this.btnI3.Name = "btnI3";
			this.btnI3.UseUnderline = true;
			this.btnI3.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w52 = new global::Gtk.Image();
			this.btnI3.Image = w52;
			this.tbUI.Add(this.btnI3);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI3]));
			w53.TopAttach = ((uint)(1));
			w53.BottomAttach = ((uint)(2));
			w53.LeftAttach = ((uint)(17));
			w53.RightAttach = ((uint)(18));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI4 = new global::Gtk.Button();
			this.btnI4.WidthRequest = 50;
			this.btnI4.HeightRequest = 50;
			this.btnI4.CanFocus = true;
			this.btnI4.Name = "btnI4";
			this.btnI4.UseUnderline = true;
			this.btnI4.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w54 = new global::Gtk.Image();
			this.btnI4.Image = w54;
			this.tbUI.Add(this.btnI4);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI4]));
			w55.TopAttach = ((uint)(1));
			w55.BottomAttach = ((uint)(2));
			w55.LeftAttach = ((uint)(18));
			w55.RightAttach = ((uint)(19));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI5 = new global::Gtk.Button();
			this.btnI5.WidthRequest = 50;
			this.btnI5.HeightRequest = 50;
			this.btnI5.CanFocus = true;
			this.btnI5.Name = "btnI5";
			this.btnI5.UseUnderline = true;
			this.btnI5.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w56 = new global::Gtk.Image();
			this.btnI5.Image = w56;
			this.tbUI.Add(this.btnI5);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI5]));
			w57.TopAttach = ((uint)(1));
			w57.BottomAttach = ((uint)(2));
			w57.LeftAttach = ((uint)(19));
			w57.RightAttach = ((uint)(20));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI6 = new global::Gtk.Button();
			this.btnI6.WidthRequest = 50;
			this.btnI6.HeightRequest = 50;
			this.btnI6.CanFocus = true;
			this.btnI6.Name = "btnI6";
			this.btnI6.UseUnderline = true;
			this.btnI6.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w58 = new global::Gtk.Image();
			this.btnI6.Image = w58;
			this.tbUI.Add(this.btnI6);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI6]));
			w59.TopAttach = ((uint)(2));
			w59.BottomAttach = ((uint)(3));
			w59.LeftAttach = ((uint)(15));
			w59.RightAttach = ((uint)(16));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI8 = new global::Gtk.Button();
			this.btnI8.WidthRequest = 50;
			this.btnI8.HeightRequest = 50;
			this.btnI8.CanFocus = true;
			this.btnI8.Name = "btnI8";
			this.btnI8.UseUnderline = true;
			this.btnI8.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w60 = new global::Gtk.Image();
			this.btnI8.Image = w60;
			this.tbUI.Add(this.btnI8);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI8]));
			w61.TopAttach = ((uint)(2));
			w61.BottomAttach = ((uint)(3));
			w61.LeftAttach = ((uint)(17));
			w61.RightAttach = ((uint)(18));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnI9 = new global::Gtk.Button();
			this.btnI9.WidthRequest = 50;
			this.btnI9.HeightRequest = 50;
			this.btnI9.CanFocus = true;
			this.btnI9.Name = "btnI9";
			this.btnI9.UseUnderline = true;
			this.btnI9.Relief = ((global::Gtk.ReliefStyle)(1));
			global::Gtk.Image w62 = new global::Gtk.Image();
			this.btnI9.Image = w62;
			this.tbUI.Add(this.btnI9);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnI9]));
			w63.TopAttach = ((uint)(2));
			w63.BottomAttach = ((uint)(3));
			w63.LeftAttach = ((uint)(18));
			w63.RightAttach = ((uint)(19));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnIM1 = new global::Gtk.Button();
			this.btnIM1.WidthRequest = 50;
			this.btnIM1.HeightRequest = 50;
			this.btnIM1.CanFocus = true;
			this.btnIM1.Name = "btnIM1";
			this.btnIM1.UseUnderline = true;
			this.btnIM1.Label = global::Mono.Unix.Catalog.GetString("1:1");
			this.tbUI.Add(this.btnIM1);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnIM1]));
			w64.TopAttach = ((uint)(15));
			w64.BottomAttach = ((uint)(16));
			w64.LeftAttach = ((uint)(1));
			w64.RightAttach = ((uint)(2));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnIM2 = new global::Gtk.Button();
			this.btnIM2.WidthRequest = 50;
			this.btnIM2.HeightRequest = 50;
			this.btnIM2.CanFocus = true;
			this.btnIM2.Name = "btnIM2";
			this.btnIM2.UseUnderline = true;
			this.btnIM2.Label = global::Mono.Unix.Catalog.GetString("1:5");
			this.tbUI.Add(this.btnIM2);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnIM2]));
			w65.TopAttach = ((uint)(15));
			w65.BottomAttach = ((uint)(16));
			w65.LeftAttach = ((uint)(3));
			w65.RightAttach = ((uint)(4));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnIM3 = new global::Gtk.Button();
			this.btnIM3.WidthRequest = 50;
			this.btnIM3.HeightRequest = 50;
			this.btnIM3.CanFocus = true;
			this.btnIM3.Name = "btnIM3";
			this.btnIM3.UseUnderline = true;
			this.btnIM3.Label = global::Mono.Unix.Catalog.GetString("1:10");
			this.tbUI.Add(this.btnIM3);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnIM3]));
			w66.TopAttach = ((uint)(15));
			w66.BottomAttach = ((uint)(16));
			w66.LeftAttach = ((uint)(5));
			w66.RightAttach = ((uint)(6));
			w66.XOptions = ((global::Gtk.AttachOptions)(4));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnInv = new global::Gtk.Button();
			this.btnInv.WidthRequest = 50;
			this.btnInv.HeightRequest = 50;
			this.btnInv.CanFocus = true;
			this.btnInv.Name = "btnInv";
			this.btnInv.UseUnderline = true;
			this.btnInv.Label = global::Mono.Unix.Catalog.GetString("Inv");
			this.tbUI.Add(this.btnInv);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnInv]));
			w67.TopAttach = ((uint)(9));
			w67.BottomAttach = ((uint)(10));
			w67.LeftAttach = ((uint)(13));
			w67.RightAttach = ((uint)(14));
			w67.XOptions = ((global::Gtk.AttachOptions)(4));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnMap = new global::Gtk.Button();
			this.btnMap.WidthRequest = 50;
			this.btnMap.HeightRequest = 50;
			this.btnMap.CanFocus = true;
			this.btnMap.Name = "btnMap";
			this.btnMap.UseUnderline = true;
			this.btnMap.Label = global::Mono.Unix.Catalog.GetString("Map");
			this.tbUI.Add(this.btnMap);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnMap]));
			w68.TopAttach = ((uint)(9));
			w68.BottomAttach = ((uint)(10));
			w68.LeftAttach = ((uint)(7));
			w68.RightAttach = ((uint)(8));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnMusic = new global::Gtk.Button();
			this.btnMusic.WidthRequest = 50;
			this.btnMusic.HeightRequest = 50;
			this.btnMusic.CanFocus = true;
			this.btnMusic.Name = "btnMusic";
			this.btnMusic.UseUnderline = true;
			this.btnMusic.Label = global::Mono.Unix.Catalog.GetString("Music");
			this.tbUI.Add(this.btnMusic);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnMusic]));
			w69.TopAttach = ((uint)(11));
			w69.BottomAttach = ((uint)(12));
			w69.LeftAttach = ((uint)(7));
			w69.RightAttach = ((uint)(8));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP1 = new global::Gtk.Button();
			this.btnP1.WidthRequest = 50;
			this.btnP1.HeightRequest = 50;
			this.btnP1.CanFocus = true;
			this.btnP1.Name = "btnP1";
			this.btnP1.UseUnderline = true;
			this.btnP1.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w70 = new global::Gtk.Image();
			this.btnP1.Image = w70;
			this.tbUI.Add(this.btnP1);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP1]));
			w71.TopAttach = ((uint)(1));
			w71.BottomAttach = ((uint)(2));
			w71.LeftAttach = ((uint)(8));
			w71.RightAttach = ((uint)(9));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP10 = new global::Gtk.Button();
			this.btnP10.WidthRequest = 50;
			this.btnP10.HeightRequest = 50;
			this.btnP10.CanFocus = true;
			this.btnP10.Name = "btnP10";
			this.btnP10.UseUnderline = true;
			this.btnP10.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w72 = new global::Gtk.Image();
			this.btnP10.Image = w72;
			this.tbUI.Add(this.btnP10);
			global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP10]));
			w73.TopAttach = ((uint)(2));
			w73.BottomAttach = ((uint)(3));
			w73.LeftAttach = ((uint)(12));
			w73.RightAttach = ((uint)(13));
			w73.XOptions = ((global::Gtk.AttachOptions)(4));
			w73.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP11 = new global::Gtk.Button();
			this.btnP11.WidthRequest = 50;
			this.btnP11.HeightRequest = 50;
			this.btnP11.CanFocus = true;
			this.btnP11.Name = "btnP11";
			this.btnP11.UseUnderline = true;
			this.btnP11.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w74 = new global::Gtk.Image();
			this.btnP11.Image = w74;
			this.tbUI.Add(this.btnP11);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP11]));
			w75.TopAttach = ((uint)(3));
			w75.BottomAttach = ((uint)(4));
			w75.LeftAttach = ((uint)(8));
			w75.RightAttach = ((uint)(9));
			w75.XOptions = ((global::Gtk.AttachOptions)(4));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP13 = new global::Gtk.Button();
			this.btnP13.WidthRequest = 50;
			this.btnP13.HeightRequest = 50;
			this.btnP13.CanFocus = true;
			this.btnP13.Name = "btnP13";
			this.btnP13.UseUnderline = true;
			this.btnP13.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w76 = new global::Gtk.Image();
			this.btnP13.Image = w76;
			this.tbUI.Add(this.btnP13);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP13]));
			w77.TopAttach = ((uint)(3));
			w77.BottomAttach = ((uint)(4));
			w77.LeftAttach = ((uint)(10));
			w77.RightAttach = ((uint)(11));
			w77.XOptions = ((global::Gtk.AttachOptions)(4));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP14 = new global::Gtk.Button();
			this.btnP14.WidthRequest = 50;
			this.btnP14.HeightRequest = 50;
			this.btnP14.CanFocus = true;
			this.btnP14.Name = "btnP14";
			this.btnP14.UseUnderline = true;
			this.btnP14.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w78 = new global::Gtk.Image();
			this.btnP14.Image = w78;
			this.tbUI.Add(this.btnP14);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP14]));
			w79.TopAttach = ((uint)(3));
			w79.BottomAttach = ((uint)(4));
			w79.LeftAttach = ((uint)(11));
			w79.RightAttach = ((uint)(12));
			w79.XOptions = ((global::Gtk.AttachOptions)(4));
			w79.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP15 = new global::Gtk.Button();
			this.btnP15.WidthRequest = 50;
			this.btnP15.HeightRequest = 50;
			this.btnP15.CanFocus = true;
			this.btnP15.Name = "btnP15";
			this.btnP15.UseUnderline = true;
			this.btnP15.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w80 = new global::Gtk.Image();
			this.btnP15.Image = w80;
			this.tbUI.Add(this.btnP15);
			global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP15]));
			w81.TopAttach = ((uint)(3));
			w81.BottomAttach = ((uint)(4));
			w81.LeftAttach = ((uint)(12));
			w81.RightAttach = ((uint)(13));
			w81.XOptions = ((global::Gtk.AttachOptions)(4));
			w81.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP16 = new global::Gtk.Button();
			this.btnP16.WidthRequest = 50;
			this.btnP16.HeightRequest = 50;
			this.btnP16.CanFocus = true;
			this.btnP16.Name = "btnP16";
			this.btnP16.UseUnderline = true;
			this.btnP16.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w82 = new global::Gtk.Image();
			this.btnP16.Image = w82;
			this.tbUI.Add(this.btnP16);
			global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP16]));
			w83.TopAttach = ((uint)(4));
			w83.BottomAttach = ((uint)(5));
			w83.LeftAttach = ((uint)(8));
			w83.RightAttach = ((uint)(9));
			w83.XOptions = ((global::Gtk.AttachOptions)(4));
			w83.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP17 = new global::Gtk.Button();
			this.btnP17.WidthRequest = 50;
			this.btnP17.HeightRequest = 50;
			this.btnP17.CanFocus = true;
			this.btnP17.Name = "btnP17";
			this.btnP17.UseUnderline = true;
			this.btnP17.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w84 = new global::Gtk.Image();
			this.btnP17.Image = w84;
			this.tbUI.Add(this.btnP17);
			global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP17]));
			w85.TopAttach = ((uint)(4));
			w85.BottomAttach = ((uint)(5));
			w85.LeftAttach = ((uint)(9));
			w85.RightAttach = ((uint)(10));
			w85.XOptions = ((global::Gtk.AttachOptions)(4));
			w85.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP18 = new global::Gtk.Button();
			this.btnP18.WidthRequest = 50;
			this.btnP18.HeightRequest = 50;
			this.btnP18.CanFocus = true;
			this.btnP18.Name = "btnP18";
			this.btnP18.UseUnderline = true;
			this.btnP18.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w86 = new global::Gtk.Image();
			this.btnP18.Image = w86;
			this.tbUI.Add(this.btnP18);
			global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP18]));
			w87.TopAttach = ((uint)(4));
			w87.BottomAttach = ((uint)(5));
			w87.LeftAttach = ((uint)(10));
			w87.RightAttach = ((uint)(11));
			w87.XOptions = ((global::Gtk.AttachOptions)(4));
			w87.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP19 = new global::Gtk.Button();
			this.btnP19.WidthRequest = 50;
			this.btnP19.HeightRequest = 50;
			this.btnP19.CanFocus = true;
			this.btnP19.Name = "btnP19";
			this.btnP19.UseUnderline = true;
			this.btnP19.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w88 = new global::Gtk.Image();
			this.btnP19.Image = w88;
			this.tbUI.Add(this.btnP19);
			global::Gtk.Table.TableChild w89 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP19]));
			w89.TopAttach = ((uint)(4));
			w89.BottomAttach = ((uint)(5));
			w89.LeftAttach = ((uint)(11));
			w89.RightAttach = ((uint)(12));
			w89.XOptions = ((global::Gtk.AttachOptions)(4));
			w89.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP2 = new global::Gtk.Button();
			this.btnP2.WidthRequest = 50;
			this.btnP2.HeightRequest = 50;
			this.btnP2.CanFocus = true;
			this.btnP2.Name = "btnP2";
			this.btnP2.UseUnderline = true;
			this.btnP2.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w90 = new global::Gtk.Image();
			this.btnP2.Image = w90;
			this.tbUI.Add(this.btnP2);
			global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP2]));
			w91.TopAttach = ((uint)(1));
			w91.BottomAttach = ((uint)(2));
			w91.LeftAttach = ((uint)(9));
			w91.RightAttach = ((uint)(10));
			w91.XOptions = ((global::Gtk.AttachOptions)(4));
			w91.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP20 = new global::Gtk.Button();
			this.btnP20.WidthRequest = 50;
			this.btnP20.HeightRequest = 50;
			this.btnP20.CanFocus = true;
			this.btnP20.Name = "btnP20";
			this.btnP20.UseUnderline = true;
			this.btnP20.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w92 = new global::Gtk.Image();
			this.btnP20.Image = w92;
			this.tbUI.Add(this.btnP20);
			global::Gtk.Table.TableChild w93 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP20]));
			w93.TopAttach = ((uint)(4));
			w93.BottomAttach = ((uint)(5));
			w93.LeftAttach = ((uint)(12));
			w93.RightAttach = ((uint)(13));
			w93.XOptions = ((global::Gtk.AttachOptions)(4));
			w93.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP21 = new global::Gtk.Button();
			this.btnP21.WidthRequest = 50;
			this.btnP21.HeightRequest = 50;
			this.btnP21.CanFocus = true;
			this.btnP21.Name = "btnP21";
			this.btnP21.UseUnderline = true;
			this.btnP21.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w94 = new global::Gtk.Image();
			this.btnP21.Image = w94;
			this.tbUI.Add(this.btnP21);
			global::Gtk.Table.TableChild w95 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP21]));
			w95.TopAttach = ((uint)(5));
			w95.BottomAttach = ((uint)(6));
			w95.LeftAttach = ((uint)(8));
			w95.RightAttach = ((uint)(9));
			w95.XOptions = ((global::Gtk.AttachOptions)(4));
			w95.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP22 = new global::Gtk.Button();
			this.btnP22.WidthRequest = 50;
			this.btnP22.HeightRequest = 50;
			this.btnP22.CanFocus = true;
			this.btnP22.Name = "btnP22";
			this.btnP22.UseUnderline = true;
			this.btnP22.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w96 = new global::Gtk.Image();
			this.btnP22.Image = w96;
			this.tbUI.Add(this.btnP22);
			global::Gtk.Table.TableChild w97 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP22]));
			w97.TopAttach = ((uint)(5));
			w97.BottomAttach = ((uint)(6));
			w97.LeftAttach = ((uint)(9));
			w97.RightAttach = ((uint)(10));
			w97.XOptions = ((global::Gtk.AttachOptions)(4));
			w97.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP23 = new global::Gtk.Button();
			this.btnP23.WidthRequest = 50;
			this.btnP23.HeightRequest = 50;
			this.btnP23.CanFocus = true;
			this.btnP23.Name = "btnP23";
			this.btnP23.UseUnderline = true;
			this.btnP23.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w98 = new global::Gtk.Image();
			this.btnP23.Image = w98;
			this.tbUI.Add(this.btnP23);
			global::Gtk.Table.TableChild w99 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP23]));
			w99.TopAttach = ((uint)(5));
			w99.BottomAttach = ((uint)(6));
			w99.LeftAttach = ((uint)(10));
			w99.RightAttach = ((uint)(11));
			w99.XOptions = ((global::Gtk.AttachOptions)(4));
			w99.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP24 = new global::Gtk.Button();
			this.btnP24.WidthRequest = 50;
			this.btnP24.HeightRequest = 50;
			this.btnP24.CanFocus = true;
			this.btnP24.Name = "btnP24";
			this.btnP24.UseUnderline = true;
			this.btnP24.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w100 = new global::Gtk.Image();
			this.btnP24.Image = w100;
			this.tbUI.Add(this.btnP24);
			global::Gtk.Table.TableChild w101 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP24]));
			w101.TopAttach = ((uint)(5));
			w101.BottomAttach = ((uint)(6));
			w101.LeftAttach = ((uint)(11));
			w101.RightAttach = ((uint)(12));
			w101.XOptions = ((global::Gtk.AttachOptions)(4));
			w101.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP25 = new global::Gtk.Button();
			this.btnP25.WidthRequest = 50;
			this.btnP25.HeightRequest = 50;
			this.btnP25.CanFocus = true;
			this.btnP25.Name = "btnP25";
			this.btnP25.UseUnderline = true;
			this.btnP25.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w102 = new global::Gtk.Image();
			this.btnP25.Image = w102;
			this.tbUI.Add(this.btnP25);
			global::Gtk.Table.TableChild w103 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP25]));
			w103.TopAttach = ((uint)(5));
			w103.BottomAttach = ((uint)(6));
			w103.LeftAttach = ((uint)(12));
			w103.RightAttach = ((uint)(13));
			w103.XOptions = ((global::Gtk.AttachOptions)(4));
			w103.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP3 = new global::Gtk.Button();
			this.btnP3.WidthRequest = 50;
			this.btnP3.HeightRequest = 50;
			this.btnP3.CanFocus = true;
			this.btnP3.Name = "btnP3";
			this.btnP3.UseUnderline = true;
			this.btnP3.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w104 = new global::Gtk.Image();
			this.btnP3.Image = w104;
			this.tbUI.Add(this.btnP3);
			global::Gtk.Table.TableChild w105 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP3]));
			w105.TopAttach = ((uint)(1));
			w105.BottomAttach = ((uint)(2));
			w105.LeftAttach = ((uint)(10));
			w105.RightAttach = ((uint)(11));
			w105.XOptions = ((global::Gtk.AttachOptions)(4));
			w105.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP4 = new global::Gtk.Button();
			this.btnP4.WidthRequest = 50;
			this.btnP4.HeightRequest = 50;
			this.btnP4.CanFocus = true;
			this.btnP4.Name = "btnP4";
			this.btnP4.UseUnderline = true;
			this.btnP4.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w106 = new global::Gtk.Image();
			this.btnP4.Image = w106;
			this.tbUI.Add(this.btnP4);
			global::Gtk.Table.TableChild w107 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP4]));
			w107.TopAttach = ((uint)(1));
			w107.BottomAttach = ((uint)(2));
			w107.LeftAttach = ((uint)(11));
			w107.RightAttach = ((uint)(12));
			w107.XOptions = ((global::Gtk.AttachOptions)(4));
			w107.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP5 = new global::Gtk.Button();
			this.btnP5.WidthRequest = 50;
			this.btnP5.HeightRequest = 50;
			this.btnP5.CanFocus = true;
			this.btnP5.Name = "btnP5";
			this.btnP5.UseUnderline = true;
			this.btnP5.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w108 = new global::Gtk.Image();
			this.btnP5.Image = w108;
			this.tbUI.Add(this.btnP5);
			global::Gtk.Table.TableChild w109 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP5]));
			w109.TopAttach = ((uint)(1));
			w109.BottomAttach = ((uint)(2));
			w109.LeftAttach = ((uint)(12));
			w109.RightAttach = ((uint)(13));
			w109.XOptions = ((global::Gtk.AttachOptions)(4));
			w109.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP6 = new global::Gtk.Button();
			this.btnP6.WidthRequest = 50;
			this.btnP6.HeightRequest = 50;
			this.btnP6.CanFocus = true;
			this.btnP6.Name = "btnP6";
			this.btnP6.UseUnderline = true;
			this.btnP6.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w110 = new global::Gtk.Image();
			this.btnP6.Image = w110;
			this.tbUI.Add(this.btnP6);
			global::Gtk.Table.TableChild w111 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP6]));
			w111.TopAttach = ((uint)(2));
			w111.BottomAttach = ((uint)(3));
			w111.LeftAttach = ((uint)(8));
			w111.RightAttach = ((uint)(9));
			w111.XOptions = ((global::Gtk.AttachOptions)(4));
			w111.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP7 = new global::Gtk.Button();
			this.btnP7.WidthRequest = 50;
			this.btnP7.HeightRequest = 50;
			this.btnP7.CanFocus = true;
			this.btnP7.Name = "btnP7";
			this.btnP7.UseUnderline = true;
			this.btnP7.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w112 = new global::Gtk.Image();
			this.btnP7.Image = w112;
			this.tbUI.Add(this.btnP7);
			global::Gtk.Table.TableChild w113 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP7]));
			w113.TopAttach = ((uint)(2));
			w113.BottomAttach = ((uint)(3));
			w113.LeftAttach = ((uint)(9));
			w113.RightAttach = ((uint)(10));
			w113.XOptions = ((global::Gtk.AttachOptions)(4));
			w113.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP8 = new global::Gtk.Button();
			this.btnP8.WidthRequest = 50;
			this.btnP8.HeightRequest = 50;
			this.btnP8.CanFocus = true;
			this.btnP8.Name = "btnP8";
			this.btnP8.UseUnderline = true;
			this.btnP8.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w114 = new global::Gtk.Image();
			this.btnP8.Image = w114;
			this.tbUI.Add(this.btnP8);
			global::Gtk.Table.TableChild w115 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP8]));
			w115.TopAttach = ((uint)(2));
			w115.BottomAttach = ((uint)(3));
			w115.LeftAttach = ((uint)(10));
			w115.RightAttach = ((uint)(11));
			w115.XOptions = ((global::Gtk.AttachOptions)(4));
			w115.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnP9 = new global::Gtk.Button();
			this.btnP9.WidthRequest = 50;
			this.btnP9.HeightRequest = 50;
			this.btnP9.CanFocus = true;
			this.btnP9.Name = "btnP9";
			this.btnP9.UseUnderline = true;
			this.btnP9.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w116 = new global::Gtk.Image();
			this.btnP9.Image = w116;
			this.tbUI.Add(this.btnP9);
			global::Gtk.Table.TableChild w117 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnP9]));
			w117.TopAttach = ((uint)(2));
			w117.BottomAttach = ((uint)(3));
			w117.LeftAttach = ((uint)(11));
			w117.RightAttach = ((uint)(12));
			w117.XOptions = ((global::Gtk.AttachOptions)(4));
			w117.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnPause = new global::Gtk.Button();
			this.btnPause.WidthRequest = 50;
			this.btnPause.HeightRequest = 50;
			this.btnPause.CanFocus = true;
			this.btnPause.Name = "btnPause";
			this.btnPause.UseUnderline = true;
			this.btnPause.Label = global::Mono.Unix.Catalog.GetString("Pause");
			this.tbUI.Add(this.btnPause);
			global::Gtk.Table.TableChild w118 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnPause]));
			w118.TopAttach = ((uint)(11));
			w118.BottomAttach = ((uint)(12));
			w118.LeftAttach = ((uint)(13));
			w118.RightAttach = ((uint)(14));
			w118.XOptions = ((global::Gtk.AttachOptions)(4));
			w118.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.button12 = new global::Gtk.Button();
			this.button12.WidthRequest = 50;
			this.button12.HeightRequest = 50;
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			this.button12.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w119 = new global::Gtk.Image();
			this.button12.Image = w119;
			this.tbUI.Add(this.button12);
			global::Gtk.Table.TableChild w120 = ((global::Gtk.Table.TableChild)(this.tbUI[this.button12]));
			w120.TopAttach = ((uint)(3));
			w120.BottomAttach = ((uint)(4));
			w120.LeftAttach = ((uint)(9));
			w120.RightAttach = ((uint)(10));
			w120.XOptions = ((global::Gtk.AttachOptions)(4));
			w120.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG1 = new global::Gtk.Image();
			this.imgG1.WidthRequest = 50;
			this.imgG1.HeightRequest = 50;
			this.imgG1.Name = "imgG1";
			this.imgG1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-dialog-authentication", global::Gtk.IconSize.Menu);
			this.tbUI.Add(this.imgG1);
			global::Gtk.Table.TableChild w121 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG1]));
			w121.TopAttach = ((uint)(1));
			w121.BottomAttach = ((uint)(2));
			w121.LeftAttach = ((uint)(1));
			w121.RightAttach = ((uint)(2));
			w121.XOptions = ((global::Gtk.AttachOptions)(4));
			w121.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG10 = new global::Gtk.Image();
			this.imgG10.Name = "imgG10";
			this.imgG10.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-dialog-error", global::Gtk.IconSize.Menu);
			this.tbUI.Add(this.imgG10);
			global::Gtk.Table.TableChild w122 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG10]));
			w122.TopAttach = ((uint)(2));
			w122.BottomAttach = ((uint)(3));
			w122.LeftAttach = ((uint)(5));
			w122.RightAttach = ((uint)(6));
			w122.XOptions = ((global::Gtk.AttachOptions)(4));
			w122.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG11 = new global::Gtk.Image();
			this.imgG11.WidthRequest = 50;
			this.imgG11.HeightRequest = 50;
			this.imgG11.Name = "imgG11";
			this.tbUI.Add(this.imgG11);
			global::Gtk.Table.TableChild w123 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG11]));
			w123.TopAttach = ((uint)(3));
			w123.BottomAttach = ((uint)(4));
			w123.LeftAttach = ((uint)(1));
			w123.RightAttach = ((uint)(2));
			w123.XOptions = ((global::Gtk.AttachOptions)(4));
			w123.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG12 = new global::Gtk.Image();
			this.imgG12.Name = "imgG12";
			this.tbUI.Add(this.imgG12);
			global::Gtk.Table.TableChild w124 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG12]));
			w124.TopAttach = ((uint)(3));
			w124.BottomAttach = ((uint)(4));
			w124.LeftAttach = ((uint)(2));
			w124.RightAttach = ((uint)(3));
			w124.XOptions = ((global::Gtk.AttachOptions)(4));
			w124.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG13 = new global::Gtk.Image();
			this.imgG13.Name = "imgG13";
			this.tbUI.Add(this.imgG13);
			global::Gtk.Table.TableChild w125 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG13]));
			w125.TopAttach = ((uint)(3));
			w125.BottomAttach = ((uint)(4));
			w125.LeftAttach = ((uint)(3));
			w125.RightAttach = ((uint)(4));
			w125.XOptions = ((global::Gtk.AttachOptions)(4));
			w125.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG14 = new global::Gtk.Image();
			this.imgG14.Name = "imgG14";
			this.tbUI.Add(this.imgG14);
			global::Gtk.Table.TableChild w126 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG14]));
			w126.TopAttach = ((uint)(3));
			w126.BottomAttach = ((uint)(4));
			w126.LeftAttach = ((uint)(4));
			w126.RightAttach = ((uint)(5));
			w126.XOptions = ((global::Gtk.AttachOptions)(4));
			w126.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG15 = new global::Gtk.Image();
			this.imgG15.Name = "imgG15";
			this.tbUI.Add(this.imgG15);
			global::Gtk.Table.TableChild w127 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG15]));
			w127.TopAttach = ((uint)(3));
			w127.BottomAttach = ((uint)(4));
			w127.LeftAttach = ((uint)(5));
			w127.RightAttach = ((uint)(6));
			w127.XOptions = ((global::Gtk.AttachOptions)(4));
			w127.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG16 = new global::Gtk.Image();
			this.imgG16.WidthRequest = 50;
			this.imgG16.HeightRequest = 50;
			this.imgG16.Name = "imgG16";
			this.tbUI.Add(this.imgG16);
			global::Gtk.Table.TableChild w128 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG16]));
			w128.TopAttach = ((uint)(4));
			w128.BottomAttach = ((uint)(5));
			w128.LeftAttach = ((uint)(1));
			w128.RightAttach = ((uint)(2));
			w128.XOptions = ((global::Gtk.AttachOptions)(4));
			w128.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG17 = new global::Gtk.Image();
			this.imgG17.Name = "imgG17";
			this.tbUI.Add(this.imgG17);
			global::Gtk.Table.TableChild w129 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG17]));
			w129.TopAttach = ((uint)(4));
			w129.BottomAttach = ((uint)(5));
			w129.LeftAttach = ((uint)(2));
			w129.RightAttach = ((uint)(3));
			w129.XOptions = ((global::Gtk.AttachOptions)(4));
			w129.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG18 = new global::Gtk.Image();
			this.imgG18.Name = "imgG18";
			this.tbUI.Add(this.imgG18);
			global::Gtk.Table.TableChild w130 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG18]));
			w130.TopAttach = ((uint)(4));
			w130.BottomAttach = ((uint)(5));
			w130.LeftAttach = ((uint)(3));
			w130.RightAttach = ((uint)(4));
			w130.XOptions = ((global::Gtk.AttachOptions)(4));
			w130.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG19 = new global::Gtk.Image();
			this.imgG19.Name = "imgG19";
			this.tbUI.Add(this.imgG19);
			global::Gtk.Table.TableChild w131 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG19]));
			w131.TopAttach = ((uint)(4));
			w131.BottomAttach = ((uint)(5));
			w131.LeftAttach = ((uint)(4));
			w131.RightAttach = ((uint)(5));
			w131.XOptions = ((global::Gtk.AttachOptions)(4));
			w131.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG2 = new global::Gtk.Image();
			this.imgG2.Name = "imgG2";
			this.tbUI.Add(this.imgG2);
			global::Gtk.Table.TableChild w132 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG2]));
			w132.TopAttach = ((uint)(1));
			w132.BottomAttach = ((uint)(2));
			w132.LeftAttach = ((uint)(2));
			w132.RightAttach = ((uint)(3));
			w132.XOptions = ((global::Gtk.AttachOptions)(4));
			w132.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG20 = new global::Gtk.Image();
			this.imgG20.Name = "imgG20";
			this.tbUI.Add(this.imgG20);
			global::Gtk.Table.TableChild w133 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG20]));
			w133.TopAttach = ((uint)(4));
			w133.BottomAttach = ((uint)(5));
			w133.LeftAttach = ((uint)(5));
			w133.RightAttach = ((uint)(6));
			w133.XOptions = ((global::Gtk.AttachOptions)(4));
			w133.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG21 = new global::Gtk.Image();
			this.imgG21.WidthRequest = 50;
			this.imgG21.HeightRequest = 50;
			this.imgG21.Name = "imgG21";
			this.tbUI.Add(this.imgG21);
			global::Gtk.Table.TableChild w134 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG21]));
			w134.TopAttach = ((uint)(5));
			w134.BottomAttach = ((uint)(6));
			w134.LeftAttach = ((uint)(1));
			w134.RightAttach = ((uint)(2));
			w134.XOptions = ((global::Gtk.AttachOptions)(4));
			w134.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG22 = new global::Gtk.Image();
			this.imgG22.Name = "imgG22";
			this.tbUI.Add(this.imgG22);
			global::Gtk.Table.TableChild w135 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG22]));
			w135.TopAttach = ((uint)(5));
			w135.BottomAttach = ((uint)(6));
			w135.LeftAttach = ((uint)(2));
			w135.RightAttach = ((uint)(3));
			w135.XOptions = ((global::Gtk.AttachOptions)(4));
			w135.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG23 = new global::Gtk.Image();
			this.imgG23.Name = "imgG23";
			this.tbUI.Add(this.imgG23);
			global::Gtk.Table.TableChild w136 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG23]));
			w136.TopAttach = ((uint)(5));
			w136.BottomAttach = ((uint)(6));
			w136.LeftAttach = ((uint)(3));
			w136.RightAttach = ((uint)(4));
			w136.XOptions = ((global::Gtk.AttachOptions)(4));
			w136.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG24 = new global::Gtk.Image();
			this.imgG24.Name = "imgG24";
			this.tbUI.Add(this.imgG24);
			global::Gtk.Table.TableChild w137 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG24]));
			w137.TopAttach = ((uint)(5));
			w137.BottomAttach = ((uint)(6));
			w137.LeftAttach = ((uint)(4));
			w137.RightAttach = ((uint)(5));
			w137.XOptions = ((global::Gtk.AttachOptions)(4));
			w137.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG25 = new global::Gtk.Image();
			this.imgG25.Name = "imgG25";
			this.tbUI.Add(this.imgG25);
			global::Gtk.Table.TableChild w138 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG25]));
			w138.TopAttach = ((uint)(5));
			w138.BottomAttach = ((uint)(6));
			w138.LeftAttach = ((uint)(5));
			w138.RightAttach = ((uint)(6));
			w138.XOptions = ((global::Gtk.AttachOptions)(4));
			w138.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG3 = new global::Gtk.Image();
			this.imgG3.Name = "imgG3";
			this.tbUI.Add(this.imgG3);
			global::Gtk.Table.TableChild w139 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG3]));
			w139.TopAttach = ((uint)(1));
			w139.BottomAttach = ((uint)(2));
			w139.LeftAttach = ((uint)(3));
			w139.RightAttach = ((uint)(4));
			w139.XOptions = ((global::Gtk.AttachOptions)(4));
			w139.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG4 = new global::Gtk.Image();
			this.imgG4.Name = "imgG4";
			this.tbUI.Add(this.imgG4);
			global::Gtk.Table.TableChild w140 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG4]));
			w140.TopAttach = ((uint)(1));
			w140.BottomAttach = ((uint)(2));
			w140.LeftAttach = ((uint)(4));
			w140.RightAttach = ((uint)(5));
			w140.XOptions = ((global::Gtk.AttachOptions)(4));
			w140.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG5 = new global::Gtk.Image();
			this.imgG5.Name = "imgG5";
			this.tbUI.Add(this.imgG5);
			global::Gtk.Table.TableChild w141 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG5]));
			w141.TopAttach = ((uint)(1));
			w141.BottomAttach = ((uint)(2));
			w141.LeftAttach = ((uint)(5));
			w141.RightAttach = ((uint)(6));
			w141.XOptions = ((global::Gtk.AttachOptions)(4));
			w141.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG6 = new global::Gtk.Image();
			this.imgG6.WidthRequest = 50;
			this.imgG6.HeightRequest = 50;
			this.imgG6.Name = "imgG6";
			this.tbUI.Add(this.imgG6);
			global::Gtk.Table.TableChild w142 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG6]));
			w142.TopAttach = ((uint)(2));
			w142.BottomAttach = ((uint)(3));
			w142.LeftAttach = ((uint)(1));
			w142.RightAttach = ((uint)(2));
			w142.XOptions = ((global::Gtk.AttachOptions)(4));
			w142.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG7 = new global::Gtk.Image();
			this.imgG7.Name = "imgG7";
			this.tbUI.Add(this.imgG7);
			global::Gtk.Table.TableChild w143 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG7]));
			w143.TopAttach = ((uint)(2));
			w143.BottomAttach = ((uint)(3));
			w143.LeftAttach = ((uint)(2));
			w143.RightAttach = ((uint)(3));
			w143.XOptions = ((global::Gtk.AttachOptions)(4));
			w143.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG8 = new global::Gtk.Image();
			this.imgG8.Name = "imgG8";
			this.tbUI.Add(this.imgG8);
			global::Gtk.Table.TableChild w144 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG8]));
			w144.TopAttach = ((uint)(2));
			w144.BottomAttach = ((uint)(3));
			w144.LeftAttach = ((uint)(3));
			w144.RightAttach = ((uint)(4));
			w144.XOptions = ((global::Gtk.AttachOptions)(4));
			w144.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgG9 = new global::Gtk.Image();
			this.imgG9.Name = "imgG9";
			this.tbUI.Add(this.imgG9);
			global::Gtk.Table.TableChild w145 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgG9]));
			w145.TopAttach = ((uint)(2));
			w145.BottomAttach = ((uint)(3));
			w145.LeftAttach = ((uint)(4));
			w145.RightAttach = ((uint)(5));
			w145.XOptions = ((global::Gtk.AttachOptions)(4));
			w145.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI1 = new global::Gtk.Image();
			this.imgI1.WidthRequest = 50;
			this.imgI1.HeightRequest = 50;
			this.imgI1.Name = "imgI1";
			this.tbUI.Add(this.imgI1);
			global::Gtk.Table.TableChild w146 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI1]));
			w146.TopAttach = ((uint)(9));
			w146.BottomAttach = ((uint)(10));
			w146.LeftAttach = ((uint)(1));
			w146.RightAttach = ((uint)(2));
			w146.XOptions = ((global::Gtk.AttachOptions)(4));
			w146.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI10 = new global::Gtk.Image();
			this.imgI10.WidthRequest = 50;
			this.imgI10.HeightRequest = 50;
			this.imgI10.Name = "imgI10";
			this.tbUI.Add(this.imgI10);
			global::Gtk.Table.TableChild w147 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI10]));
			w147.TopAttach = ((uint)(10));
			w147.BottomAttach = ((uint)(11));
			w147.LeftAttach = ((uint)(5));
			w147.RightAttach = ((uint)(6));
			w147.XOptions = ((global::Gtk.AttachOptions)(4));
			w147.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI11 = new global::Gtk.Image();
			this.imgI11.WidthRequest = 50;
			this.imgI11.HeightRequest = 50;
			this.imgI11.Name = "imgI11";
			this.tbUI.Add(this.imgI11);
			global::Gtk.Table.TableChild w148 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI11]));
			w148.TopAttach = ((uint)(11));
			w148.BottomAttach = ((uint)(12));
			w148.LeftAttach = ((uint)(1));
			w148.RightAttach = ((uint)(2));
			w148.XOptions = ((global::Gtk.AttachOptions)(4));
			w148.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI12 = new global::Gtk.Image();
			this.imgI12.WidthRequest = 50;
			this.imgI12.HeightRequest = 50;
			this.imgI12.Name = "imgI12";
			this.tbUI.Add(this.imgI12);
			global::Gtk.Table.TableChild w149 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI12]));
			w149.TopAttach = ((uint)(11));
			w149.BottomAttach = ((uint)(12));
			w149.LeftAttach = ((uint)(2));
			w149.RightAttach = ((uint)(3));
			w149.XOptions = ((global::Gtk.AttachOptions)(4));
			w149.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI13 = new global::Gtk.Image();
			this.imgI13.WidthRequest = 50;
			this.imgI13.HeightRequest = 50;
			this.imgI13.Name = "imgI13";
			this.tbUI.Add(this.imgI13);
			global::Gtk.Table.TableChild w150 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI13]));
			w150.TopAttach = ((uint)(11));
			w150.BottomAttach = ((uint)(12));
			w150.LeftAttach = ((uint)(3));
			w150.RightAttach = ((uint)(4));
			w150.XOptions = ((global::Gtk.AttachOptions)(4));
			w150.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI14 = new global::Gtk.Image();
			this.imgI14.WidthRequest = 50;
			this.imgI14.HeightRequest = 50;
			this.imgI14.Name = "imgI14";
			this.tbUI.Add(this.imgI14);
			global::Gtk.Table.TableChild w151 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI14]));
			w151.TopAttach = ((uint)(11));
			w151.BottomAttach = ((uint)(12));
			w151.LeftAttach = ((uint)(4));
			w151.RightAttach = ((uint)(5));
			w151.XOptions = ((global::Gtk.AttachOptions)(4));
			w151.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI15 = new global::Gtk.Image();
			this.imgI15.WidthRequest = 50;
			this.imgI15.HeightRequest = 50;
			this.imgI15.Name = "imgI15";
			this.tbUI.Add(this.imgI15);
			global::Gtk.Table.TableChild w152 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI15]));
			w152.TopAttach = ((uint)(11));
			w152.BottomAttach = ((uint)(12));
			w152.LeftAttach = ((uint)(5));
			w152.RightAttach = ((uint)(6));
			w152.XOptions = ((global::Gtk.AttachOptions)(4));
			w152.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI16 = new global::Gtk.Image();
			this.imgI16.WidthRequest = 50;
			this.imgI16.HeightRequest = 50;
			this.imgI16.Name = "imgI16";
			this.tbUI.Add(this.imgI16);
			global::Gtk.Table.TableChild w153 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI16]));
			w153.TopAttach = ((uint)(12));
			w153.BottomAttach = ((uint)(13));
			w153.LeftAttach = ((uint)(1));
			w153.RightAttach = ((uint)(2));
			w153.XOptions = ((global::Gtk.AttachOptions)(4));
			w153.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI17 = new global::Gtk.Image();
			this.imgI17.WidthRequest = 50;
			this.imgI17.HeightRequest = 50;
			this.imgI17.Name = "imgI17";
			this.tbUI.Add(this.imgI17);
			global::Gtk.Table.TableChild w154 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI17]));
			w154.TopAttach = ((uint)(12));
			w154.BottomAttach = ((uint)(13));
			w154.LeftAttach = ((uint)(2));
			w154.RightAttach = ((uint)(3));
			w154.XOptions = ((global::Gtk.AttachOptions)(4));
			w154.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI18 = new global::Gtk.Image();
			this.imgI18.WidthRequest = 50;
			this.imgI18.HeightRequest = 50;
			this.imgI18.Name = "imgI18";
			this.tbUI.Add(this.imgI18);
			global::Gtk.Table.TableChild w155 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI18]));
			w155.TopAttach = ((uint)(12));
			w155.BottomAttach = ((uint)(13));
			w155.LeftAttach = ((uint)(3));
			w155.RightAttach = ((uint)(4));
			w155.XOptions = ((global::Gtk.AttachOptions)(4));
			w155.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI19 = new global::Gtk.Image();
			this.imgI19.WidthRequest = 50;
			this.imgI19.HeightRequest = 50;
			this.imgI19.Name = "imgI19";
			this.tbUI.Add(this.imgI19);
			global::Gtk.Table.TableChild w156 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI19]));
			w156.TopAttach = ((uint)(12));
			w156.BottomAttach = ((uint)(13));
			w156.LeftAttach = ((uint)(4));
			w156.RightAttach = ((uint)(5));
			w156.XOptions = ((global::Gtk.AttachOptions)(4));
			w156.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI2 = new global::Gtk.Image();
			this.imgI2.WidthRequest = 50;
			this.imgI2.HeightRequest = 50;
			this.imgI2.Name = "imgI2";
			this.tbUI.Add(this.imgI2);
			global::Gtk.Table.TableChild w157 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI2]));
			w157.TopAttach = ((uint)(9));
			w157.BottomAttach = ((uint)(10));
			w157.LeftAttach = ((uint)(2));
			w157.RightAttach = ((uint)(3));
			w157.XOptions = ((global::Gtk.AttachOptions)(4));
			w157.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI20 = new global::Gtk.Image();
			this.imgI20.WidthRequest = 50;
			this.imgI20.HeightRequest = 50;
			this.imgI20.Name = "imgI20";
			this.tbUI.Add(this.imgI20);
			global::Gtk.Table.TableChild w158 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI20]));
			w158.TopAttach = ((uint)(12));
			w158.BottomAttach = ((uint)(13));
			w158.LeftAttach = ((uint)(5));
			w158.RightAttach = ((uint)(6));
			w158.XOptions = ((global::Gtk.AttachOptions)(4));
			w158.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI21 = new global::Gtk.Image();
			this.imgI21.WidthRequest = 50;
			this.imgI21.HeightRequest = 50;
			this.imgI21.Name = "imgI21";
			this.tbUI.Add(this.imgI21);
			global::Gtk.Table.TableChild w159 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI21]));
			w159.TopAttach = ((uint)(13));
			w159.BottomAttach = ((uint)(14));
			w159.LeftAttach = ((uint)(1));
			w159.RightAttach = ((uint)(2));
			w159.XOptions = ((global::Gtk.AttachOptions)(4));
			w159.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI22 = new global::Gtk.Image();
			this.imgI22.WidthRequest = 50;
			this.imgI22.HeightRequest = 50;
			this.imgI22.Name = "imgI22";
			this.tbUI.Add(this.imgI22);
			global::Gtk.Table.TableChild w160 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI22]));
			w160.TopAttach = ((uint)(13));
			w160.BottomAttach = ((uint)(14));
			w160.LeftAttach = ((uint)(2));
			w160.RightAttach = ((uint)(3));
			w160.XOptions = ((global::Gtk.AttachOptions)(4));
			w160.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI23 = new global::Gtk.Image();
			this.imgI23.WidthRequest = 50;
			this.imgI23.HeightRequest = 50;
			this.imgI23.Name = "imgI23";
			this.tbUI.Add(this.imgI23);
			global::Gtk.Table.TableChild w161 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI23]));
			w161.TopAttach = ((uint)(13));
			w161.BottomAttach = ((uint)(14));
			w161.LeftAttach = ((uint)(3));
			w161.RightAttach = ((uint)(4));
			w161.XOptions = ((global::Gtk.AttachOptions)(4));
			w161.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI24 = new global::Gtk.Image();
			this.imgI24.WidthRequest = 50;
			this.imgI24.HeightRequest = 50;
			this.imgI24.Name = "imgI24";
			this.tbUI.Add(this.imgI24);
			global::Gtk.Table.TableChild w162 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI24]));
			w162.TopAttach = ((uint)(13));
			w162.BottomAttach = ((uint)(14));
			w162.LeftAttach = ((uint)(4));
			w162.RightAttach = ((uint)(5));
			w162.XOptions = ((global::Gtk.AttachOptions)(4));
			w162.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI25 = new global::Gtk.Image();
			this.imgI25.WidthRequest = 50;
			this.imgI25.HeightRequest = 50;
			this.imgI25.Name = "imgI25";
			this.tbUI.Add(this.imgI25);
			global::Gtk.Table.TableChild w163 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI25]));
			w163.TopAttach = ((uint)(13));
			w163.BottomAttach = ((uint)(14));
			w163.LeftAttach = ((uint)(5));
			w163.RightAttach = ((uint)(6));
			w163.XOptions = ((global::Gtk.AttachOptions)(4));
			w163.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI3 = new global::Gtk.Image();
			this.imgI3.WidthRequest = 50;
			this.imgI3.HeightRequest = 50;
			this.imgI3.Name = "imgI3";
			this.tbUI.Add(this.imgI3);
			global::Gtk.Table.TableChild w164 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI3]));
			w164.TopAttach = ((uint)(9));
			w164.BottomAttach = ((uint)(10));
			w164.LeftAttach = ((uint)(3));
			w164.RightAttach = ((uint)(4));
			w164.XOptions = ((global::Gtk.AttachOptions)(4));
			w164.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI4 = new global::Gtk.Image();
			this.imgI4.WidthRequest = 50;
			this.imgI4.HeightRequest = 50;
			this.imgI4.Name = "imgI4";
			this.tbUI.Add(this.imgI4);
			global::Gtk.Table.TableChild w165 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI4]));
			w165.TopAttach = ((uint)(9));
			w165.BottomAttach = ((uint)(10));
			w165.LeftAttach = ((uint)(4));
			w165.RightAttach = ((uint)(5));
			w165.XOptions = ((global::Gtk.AttachOptions)(4));
			w165.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI5 = new global::Gtk.Image();
			this.imgI5.WidthRequest = 50;
			this.imgI5.HeightRequest = 50;
			this.imgI5.Name = "imgI5";
			this.tbUI.Add(this.imgI5);
			global::Gtk.Table.TableChild w166 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI5]));
			w166.TopAttach = ((uint)(9));
			w166.BottomAttach = ((uint)(10));
			w166.LeftAttach = ((uint)(5));
			w166.RightAttach = ((uint)(6));
			w166.XOptions = ((global::Gtk.AttachOptions)(4));
			w166.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI6 = new global::Gtk.Image();
			this.imgI6.WidthRequest = 50;
			this.imgI6.HeightRequest = 50;
			this.imgI6.Name = "imgI6";
			this.tbUI.Add(this.imgI6);
			global::Gtk.Table.TableChild w167 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI6]));
			w167.TopAttach = ((uint)(10));
			w167.BottomAttach = ((uint)(11));
			w167.LeftAttach = ((uint)(1));
			w167.RightAttach = ((uint)(2));
			w167.XOptions = ((global::Gtk.AttachOptions)(4));
			w167.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI7 = new global::Gtk.Image();
			this.imgI7.WidthRequest = 50;
			this.imgI7.HeightRequest = 50;
			this.imgI7.Name = "imgI7";
			this.tbUI.Add(this.imgI7);
			global::Gtk.Table.TableChild w168 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI7]));
			w168.TopAttach = ((uint)(10));
			w168.BottomAttach = ((uint)(11));
			w168.LeftAttach = ((uint)(2));
			w168.RightAttach = ((uint)(3));
			w168.XOptions = ((global::Gtk.AttachOptions)(4));
			w168.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI8 = new global::Gtk.Image();
			this.imgI8.WidthRequest = 50;
			this.imgI8.HeightRequest = 50;
			this.imgI8.Name = "imgI8";
			this.tbUI.Add(this.imgI8);
			global::Gtk.Table.TableChild w169 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI8]));
			w169.TopAttach = ((uint)(10));
			w169.BottomAttach = ((uint)(11));
			w169.LeftAttach = ((uint)(3));
			w169.RightAttach = ((uint)(4));
			w169.XOptions = ((global::Gtk.AttachOptions)(4));
			w169.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgI9 = new global::Gtk.Image();
			this.imgI9.WidthRequest = 50;
			this.imgI9.HeightRequest = 50;
			this.imgI9.Name = "imgI9";
			this.tbUI.Add(this.imgI9);
			global::Gtk.Table.TableChild w170 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgI9]));
			w170.TopAttach = ((uint)(10));
			w170.BottomAttach = ((uint)(11));
			w170.LeftAttach = ((uint)(4));
			w170.RightAttach = ((uint)(5));
			w170.XOptions = ((global::Gtk.AttachOptions)(4));
			w170.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgS1 = new global::Gtk.Image();
			this.imgS1.WidthRequest = 50;
			this.imgS1.HeightRequest = 50;
			this.imgS1.Name = "imgS1";
			this.tbUI.Add(this.imgS1);
			global::Gtk.Table.TableChild w171 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgS1]));
			w171.TopAttach = ((uint)(7));
			w171.BottomAttach = ((uint)(8));
			w171.LeftAttach = ((uint)(8));
			w171.RightAttach = ((uint)(9));
			w171.XOptions = ((global::Gtk.AttachOptions)(4));
			w171.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgS10 = new global::Gtk.Image();
			this.imgS10.WidthRequest = 50;
			this.imgS10.HeightRequest = 50;
			this.imgS10.Name = "imgS10";
			this.tbUI.Add(this.imgS10);
			global::Gtk.Table.TableChild w172 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgS10]));
			w172.TopAttach = ((uint)(8));
			w172.BottomAttach = ((uint)(9));
			w172.LeftAttach = ((uint)(12));
			w172.RightAttach = ((uint)(13));
			w172.XOptions = ((global::Gtk.AttachOptions)(4));
			w172.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgS2 = new global::Gtk.Image();
			this.imgS2.WidthRequest = 50;
			this.imgS2.HeightRequest = 50;
			this.imgS2.Name = "imgS2";
			this.tbUI.Add(this.imgS2);
			global::Gtk.Table.TableChild w173 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgS2]));
			w173.TopAttach = ((uint)(7));
			w173.BottomAttach = ((uint)(8));
			w173.LeftAttach = ((uint)(9));
			w173.RightAttach = ((uint)(10));
			w173.XOptions = ((global::Gtk.AttachOptions)(4));
			w173.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgS3 = new global::Gtk.Image();
			this.imgS3.WidthRequest = 50;
			this.imgS3.HeightRequest = 50;
			this.imgS3.Name = "imgS3";
			this.tbUI.Add(this.imgS3);
			global::Gtk.Table.TableChild w174 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgS3]));
			w174.TopAttach = ((uint)(7));
			w174.BottomAttach = ((uint)(8));
			w174.LeftAttach = ((uint)(10));
			w174.RightAttach = ((uint)(11));
			w174.XOptions = ((global::Gtk.AttachOptions)(4));
			w174.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgS4 = new global::Gtk.Image();
			this.imgS4.WidthRequest = 50;
			this.imgS4.HeightRequest = 50;
			this.imgS4.Name = "imgS4";
			this.tbUI.Add(this.imgS4);
			global::Gtk.Table.TableChild w175 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgS4]));
			w175.TopAttach = ((uint)(7));
			w175.BottomAttach = ((uint)(8));
			w175.LeftAttach = ((uint)(11));
			w175.RightAttach = ((uint)(12));
			w175.XOptions = ((global::Gtk.AttachOptions)(4));
			w175.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgS5 = new global::Gtk.Image();
			this.imgS5.WidthRequest = 50;
			this.imgS5.HeightRequest = 50;
			this.imgS5.Name = "imgS5";
			this.tbUI.Add(this.imgS5);
			global::Gtk.Table.TableChild w176 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgS5]));
			w176.TopAttach = ((uint)(7));
			w176.BottomAttach = ((uint)(8));
			w176.LeftAttach = ((uint)(12));
			w176.RightAttach = ((uint)(13));
			w176.XOptions = ((global::Gtk.AttachOptions)(4));
			w176.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgS6 = new global::Gtk.Image();
			this.imgS6.WidthRequest = 50;
			this.imgS6.HeightRequest = 50;
			this.imgS6.Name = "imgS6";
			this.tbUI.Add(this.imgS6);
			global::Gtk.Table.TableChild w177 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgS6]));
			w177.TopAttach = ((uint)(8));
			w177.BottomAttach = ((uint)(9));
			w177.LeftAttach = ((uint)(8));
			w177.RightAttach = ((uint)(9));
			w177.XOptions = ((global::Gtk.AttachOptions)(4));
			w177.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgS7 = new global::Gtk.Image();
			this.imgS7.WidthRequest = 50;
			this.imgS7.HeightRequest = 50;
			this.imgS7.Name = "imgS7";
			this.tbUI.Add(this.imgS7);
			global::Gtk.Table.TableChild w178 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgS7]));
			w178.TopAttach = ((uint)(8));
			w178.BottomAttach = ((uint)(9));
			w178.LeftAttach = ((uint)(9));
			w178.RightAttach = ((uint)(10));
			w178.XOptions = ((global::Gtk.AttachOptions)(4));
			w178.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgS8 = new global::Gtk.Image();
			this.imgS8.WidthRequest = 50;
			this.imgS8.HeightRequest = 50;
			this.imgS8.Name = "imgS8";
			this.tbUI.Add(this.imgS8);
			global::Gtk.Table.TableChild w179 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgS8]));
			w179.TopAttach = ((uint)(8));
			w179.BottomAttach = ((uint)(9));
			w179.LeftAttach = ((uint)(10));
			w179.RightAttach = ((uint)(11));
			w179.XOptions = ((global::Gtk.AttachOptions)(4));
			w179.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.imgS9 = new global::Gtk.Image();
			this.imgS9.WidthRequest = 50;
			this.imgS9.HeightRequest = 50;
			this.imgS9.Name = "imgS9";
			this.tbUI.Add(this.imgS9);
			global::Gtk.Table.TableChild w180 = ((global::Gtk.Table.TableChild)(this.tbUI[this.imgS9]));
			w180.TopAttach = ((uint)(8));
			w180.BottomAttach = ((uint)(9));
			w180.LeftAttach = ((uint)(11));
			w180.RightAttach = ((uint)(12));
			w180.XOptions = ((global::Gtk.AttachOptions)(4));
			w180.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank1 = new global::Gtk.Label();
			this.lblBlank1.WidthRequest = 25;
			this.lblBlank1.HeightRequest = 50;
			this.lblBlank1.Name = "lblBlank1";
			this.tbUI.Add(this.lblBlank1);
			global::Gtk.Table.TableChild w181 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank1]));
			w181.TopAttach = ((uint)(3));
			w181.BottomAttach = ((uint)(4));
			w181.LeftAttach = ((uint)(6));
			w181.RightAttach = ((uint)(7));
			w181.XOptions = ((global::Gtk.AttachOptions)(4));
			w181.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank2 = new global::Gtk.Label();
			this.lblBlank2.WidthRequest = 50;
			this.lblBlank2.HeightRequest = 25;
			this.lblBlank2.Name = "lblBlank2";
			this.tbUI.Add(this.lblBlank2);
			global::Gtk.Table.TableChild w182 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank2]));
			w182.TopAttach = ((uint)(6));
			w182.BottomAttach = ((uint)(7));
			w182.LeftAttach = ((uint)(10));
			w182.RightAttach = ((uint)(11));
			w182.XOptions = ((global::Gtk.AttachOptions)(4));
			w182.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank3 = new global::Gtk.Label();
			this.lblBlank3.WidthRequest = 25;
			this.lblBlank3.HeightRequest = 50;
			this.lblBlank3.Name = "lblBlank3";
			this.tbUI.Add(this.lblBlank3);
			global::Gtk.Table.TableChild w183 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank3]));
			w183.TopAttach = ((uint)(3));
			w183.BottomAttach = ((uint)(4));
			w183.LeftAttach = ((uint)(14));
			w183.RightAttach = ((uint)(15));
			w183.XOptions = ((global::Gtk.AttachOptions)(4));
			w183.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank4 = new global::Gtk.Label();
			this.lblBlank4.WidthRequest = 10;
			this.lblBlank4.HeightRequest = 50;
			this.lblBlank4.Name = "lblBlank4";
			this.tbUI.Add(this.lblBlank4);
			global::Gtk.Table.TableChild w184 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank4]));
			w184.TopAttach = ((uint)(3));
			w184.BottomAttach = ((uint)(4));
			w184.LeftAttach = ((uint)(20));
			w184.RightAttach = ((uint)(21));
			w184.XOptions = ((global::Gtk.AttachOptions)(4));
			w184.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank5 = new global::Gtk.Label();
			this.lblBlank5.WidthRequest = 10;
			this.lblBlank5.HeightRequest = 50;
			this.lblBlank5.Name = "lblBlank5";
			this.tbUI.Add(this.lblBlank5);
			global::Gtk.Table.TableChild w185 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank5]));
			w185.TopAttach = ((uint)(3));
			w185.BottomAttach = ((uint)(4));
			w185.XOptions = ((global::Gtk.AttachOptions)(4));
			w185.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank6 = new global::Gtk.Label();
			this.lblBlank6.WidthRequest = 50;
			this.lblBlank6.HeightRequest = 25;
			this.lblBlank6.Name = "lblBlank6";
			this.tbUI.Add(this.lblBlank6);
			global::Gtk.Table.TableChild w186 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank6]));
			w186.TopAttach = ((uint)(9));
			w186.BottomAttach = ((uint)(10));
			w186.LeftAttach = ((uint)(10));
			w186.RightAttach = ((uint)(11));
			w186.XOptions = ((global::Gtk.AttachOptions)(4));
			w186.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank7 = new global::Gtk.Label();
			this.lblBlank7.WidthRequest = 50;
			this.lblBlank7.HeightRequest = 50;
			this.lblBlank7.Name = "lblBlank7";
			this.tbUI.Add(this.lblBlank7);
			global::Gtk.Table.TableChild w187 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank7]));
			w187.TopAttach = ((uint)(11));
			w187.BottomAttach = ((uint)(12));
			w187.LeftAttach = ((uint)(10));
			w187.RightAttach = ((uint)(11));
			w187.XOptions = ((global::Gtk.AttachOptions)(4));
			w187.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank8 = new global::Gtk.Label();
			this.lblBlank8.WidthRequest = 50;
			this.lblBlank8.HeightRequest = 10;
			this.lblBlank8.Name = "lblBlank8";
			this.tbUI.Add(this.lblBlank8);
			global::Gtk.Table.TableChild w188 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank8]));
			w188.TopAttach = ((uint)(16));
			w188.BottomAttach = ((uint)(17));
			w188.LeftAttach = ((uint)(10));
			w188.RightAttach = ((uint)(11));
			w188.XOptions = ((global::Gtk.AttachOptions)(4));
			w188.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank9 = new global::Gtk.Label();
			this.lblBlank9.WidthRequest = 50;
			this.lblBlank9.HeightRequest = 10;
			this.lblBlank9.Name = "lblBlank9";
			this.tbUI.Add(this.lblBlank9);
			global::Gtk.Table.TableChild w189 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank9]));
			w189.LeftAttach = ((uint)(10));
			w189.RightAttach = ((uint)(11));
			w189.XOptions = ((global::Gtk.AttachOptions)(4));
			w189.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblLog1 = new global::Gtk.Label();
			this.lblLog1.HeightRequest = 50;
			this.lblLog1.Name = "lblLog1";
			this.lblLog1.LabelProp = global::Mono.Unix.Catalog.GetString("label6");
			this.tbUI.Add(this.lblLog1);
			global::Gtk.Table.TableChild w190 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblLog1]));
			w190.TopAttach = ((uint)(12));
			w190.BottomAttach = ((uint)(13));
			w190.LeftAttach = ((uint)(8));
			w190.RightAttach = ((uint)(13));
			w190.XOptions = ((global::Gtk.AttachOptions)(4));
			w190.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblLog2 = new global::Gtk.Label();
			this.lblLog2.HeightRequest = 50;
			this.lblLog2.Name = "lblLog2";
			this.lblLog2.LabelProp = global::Mono.Unix.Catalog.GetString("label7");
			this.tbUI.Add(this.lblLog2);
			global::Gtk.Table.TableChild w191 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblLog2]));
			w191.TopAttach = ((uint)(13));
			w191.BottomAttach = ((uint)(14));
			w191.LeftAttach = ((uint)(8));
			w191.RightAttach = ((uint)(13));
			w191.XOptions = ((global::Gtk.AttachOptions)(4));
			w191.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblLog3 = new global::Gtk.Label();
			this.lblLog3.HeightRequest = 50;
			this.lblLog3.Name = "lblLog3";
			this.lblLog3.LabelProp = global::Mono.Unix.Catalog.GetString("label7");
			this.tbUI.Add(this.lblLog3);
			global::Gtk.Table.TableChild w192 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblLog3]));
			w192.TopAttach = ((uint)(14));
			w192.BottomAttach = ((uint)(15));
			w192.LeftAttach = ((uint)(8));
			w192.RightAttach = ((uint)(13));
			w192.XOptions = ((global::Gtk.AttachOptions)(4));
			w192.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblLog4 = new global::Gtk.Label();
			this.lblLog4.HeightRequest = 50;
			this.lblLog4.Name = "lblLog4";
			this.lblLog4.LabelProp = global::Mono.Unix.Catalog.GetString("label7");
			this.tbUI.Add(this.lblLog4);
			global::Gtk.Table.TableChild w193 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblLog4]));
			w193.TopAttach = ((uint)(15));
			w193.BottomAttach = ((uint)(16));
			w193.LeftAttach = ((uint)(8));
			w193.RightAttach = ((uint)(13));
			w193.XOptions = ((global::Gtk.AttachOptions)(4));
			w193.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.tbUI);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 920;
			this.DefaultHeight = 745;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		}
	}
}
