
// This file has been generated by the GUI designer. Do not modify.
namespace Mundus.Views.Windows
{
	public partial class MusicWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Table tbUI;

		private global::Gtk.Button btnBack;

		private global::Gtk.Button btnNext;

		private global::Gtk.Button btnPlay;

		private global::Gtk.Button btnPrevious;

		private global::Gtk.Button btnRandom;

		private global::Gtk.Button btnStop;

		private global::Gtk.FileChooserWidget fcMusic;

		private global::Gtk.HSeparator hSeparator;

		private global::Gtk.Label lblBlank1;

		private global::Gtk.Label lblBlank2;

		private global::Gtk.Label lblPath;

		private global::Gtk.Label lblTitle;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Mundus.Views.Windows.MusicWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Mundus.Views.Windows.MusicWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MusicWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Mundus.Views.Windows.MusicWindow.Gtk.Container+ContainerChild
			this.tbUI = new global::Gtk.Table(((uint)(5)), ((uint)(7)), false);
			this.tbUI.Name = "tbUI";
			this.tbUI.RowSpacing = ((uint)(3));
			this.tbUI.ColumnSpacing = ((uint)(6));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnBack = new global::Gtk.Button();
			this.btnBack.WidthRequest = 50;
			this.btnBack.HeightRequest = 50;
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.BorderWidth = ((uint)(3));
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString("Back");
			this.tbUI.Add(this.btnBack);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnBack]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnNext = new global::Gtk.Button();
			this.btnNext.WidthRequest = 70;
			this.btnNext.HeightRequest = 50;
			this.btnNext.CanFocus = true;
			this.btnNext.Name = "btnNext";
			this.btnNext.UseUnderline = true;
			this.btnNext.Label = global::Mono.Unix.Catalog.GetString("Next");
			this.tbUI.Add(this.btnNext);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnNext]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(4));
			w3.RightAttach = ((uint)(5));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnPlay = new global::Gtk.Button();
			this.btnPlay.WidthRequest = 70;
			this.btnPlay.HeightRequest = 50;
			this.btnPlay.CanFocus = true;
			this.btnPlay.Name = "btnPlay";
			this.btnPlay.UseUnderline = true;
			this.btnPlay.Label = global::Mono.Unix.Catalog.GetString("Play");
			this.tbUI.Add(this.btnPlay);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnPlay]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnPrevious = new global::Gtk.Button();
			this.btnPrevious.WidthRequest = 70;
			this.btnPrevious.HeightRequest = 50;
			this.btnPrevious.CanFocus = true;
			this.btnPrevious.Name = "btnPrevious";
			this.btnPrevious.UseUnderline = true;
			this.btnPrevious.Label = global::Mono.Unix.Catalog.GetString("Prev");
			this.tbUI.Add(this.btnPrevious);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnPrevious]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(3));
			w5.RightAttach = ((uint)(4));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnRandom = new global::Gtk.Button();
			this.btnRandom.WidthRequest = 70;
			this.btnRandom.HeightRequest = 50;
			this.btnRandom.CanFocus = true;
			this.btnRandom.Name = "btnRandom";
			this.btnRandom.UseUnderline = true;
			this.btnRandom.Label = global::Mono.Unix.Catalog.GetString("Rnd");
			this.tbUI.Add(this.btnRandom);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnRandom]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(5));
			w6.RightAttach = ((uint)(6));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnStop = new global::Gtk.Button();
			this.btnStop.WidthRequest = 70;
			this.btnStop.HeightRequest = 50;
			this.btnStop.CanFocus = true;
			this.btnStop.Name = "btnStop";
			this.btnStop.UseUnderline = true;
			this.btnStop.Label = global::Mono.Unix.Catalog.GetString("Stop");
			this.tbUI.Add(this.btnStop);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnStop]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.fcMusic = new global::Gtk.FileChooserWidget(((global::Gtk.FileChooserAction)(0)));
			this.fcMusic.Name = "fcMusic";
			this.fcMusic.LocalOnly = false;
			this.tbUI.Add(this.fcMusic);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tbUI[this.fcMusic]));
			w8.TopAttach = ((uint)(4));
			w8.BottomAttach = ((uint)(5));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(6));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.hSeparator = new global::Gtk.HSeparator();
			this.hSeparator.HeightRequest = 5;
			this.hSeparator.Name = "hSeparator";
			this.tbUI.Add(this.hSeparator);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tbUI[this.hSeparator]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(6));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank1 = new global::Gtk.Label();
			this.lblBlank1.WidthRequest = 5;
			this.lblBlank1.HeightRequest = 50;
			this.lblBlank1.Name = "lblBlank1";
			this.lblBlank1.LabelProp = "";
			this.tbUI.Add(this.lblBlank1);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank1]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank2 = new global::Gtk.Label();
			this.lblBlank2.WidthRequest = 5;
			this.lblBlank2.HeightRequest = 50;
			this.lblBlank2.Name = "lblBlank2";
			this.lblBlank2.LabelProp = "";
			this.tbUI.Add(this.lblBlank2);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank2]));
			w11.LeftAttach = ((uint)(6));
			w11.RightAttach = ((uint)(7));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblPath = new global::Gtk.Label();
			this.lblPath.HeightRequest = 50;
			this.lblPath.Name = "lblPath";
			this.lblPath.LabelProp = global::Mono.Unix.Catalog.GetString("No file chosen");
			this.lblPath.Wrap = true;
			this.lblPath.Justify = ((global::Gtk.Justification)(2));
			this.lblPath.Selectable = true;
			this.tbUI.Add(this.lblPath);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblPath]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(6));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblTitle = new global::Gtk.Label();
			this.lblTitle.Name = "lblTitle";
			this.lblTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Music (replace with picture)");
			this.tbUI.Add(this.lblTitle);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblTitle]));
			w13.LeftAttach = ((uint)(2));
			w13.RightAttach = ((uint)(6));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.tbUI);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 406;
			this.DefaultHeight = 549;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.fcMusic.SelectionChanged += new global::System.EventHandler(this.OnFcMusicSelectionChanged);
			this.btnStop.Clicked += new global::System.EventHandler(this.OnBtnStopClicked);
			this.btnRandom.Clicked += new global::System.EventHandler(this.OnBtnPlayClicked);
			this.btnPlay.Clicked += new global::System.EventHandler(this.OnBtnPlayClicked);
			this.btnNext.Clicked += new global::System.EventHandler(this.OnBtnNextClicked);
			this.btnBack.Clicked += new global::System.EventHandler(this.OnBtnBackClicked);
		}
	}
}
