
// This file has been generated by the GUI designer. Do not modify.
namespace Mundus.Views.Windows
{
	public partial class PauseWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button btnBack;

		private global::Gtk.Label lblTitle;

		private global::Gtk.HSeparator hSeparator;

		private global::Gtk.Button btnSettings;

		private global::Gtk.Button btnSave;

		private global::Gtk.Button btnSaveExit;

		private global::Gtk.Button btnExit;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Mundus.Views.Windows.PauseWindow
			this.Name = "Mundus.Views.Windows.PauseWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("PauseWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Mundus.Views.Windows.PauseWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnBack = new global::Gtk.Button();
			this.btnBack.WidthRequest = 50;
			this.btnBack.HeightRequest = 50;
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString("Back");
			this.hbox1.Add(this.btnBack);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnBack]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblTitle = new global::Gtk.Label();
			this.lblTitle.Name = "lblTitle";
			this.lblTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Pause menu (replace with picture)");
			this.hbox1.Add(this.lblTitle);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblTitle]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(3));
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hSeparator = new global::Gtk.HSeparator();
			this.hSeparator.HeightRequest = 5;
			this.hSeparator.Name = "hSeparator";
			this.vbox1.Add(this.hSeparator);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hSeparator]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnSettings = new global::Gtk.Button();
			this.btnSettings.HeightRequest = 50;
			this.btnSettings.CanFocus = true;
			this.btnSettings.Name = "btnSettings";
			this.btnSettings.UseUnderline = true;
			this.btnSettings.BorderWidth = ((uint)(3));
			this.btnSettings.Label = global::Mono.Unix.Catalog.GetString("Settings");
			this.vbox1.Add(this.btnSettings);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.btnSettings]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnSave = new global::Gtk.Button();
			this.btnSave.HeightRequest = 50;
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.BorderWidth = ((uint)(3));
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString("Save");
			this.vbox1.Add(this.btnSave);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.btnSave]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnSaveExit = new global::Gtk.Button();
			this.btnSaveExit.HeightRequest = 50;
			this.btnSaveExit.CanFocus = true;
			this.btnSaveExit.Name = "btnSaveExit";
			this.btnSaveExit.UseUnderline = true;
			this.btnSaveExit.BorderWidth = ((uint)(3));
			this.btnSaveExit.Label = global::Mono.Unix.Catalog.GetString("Save & Exit");
			this.vbox1.Add(this.btnSaveExit);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.btnSaveExit]));
			w7.Position = 4;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnExit = new global::Gtk.Button();
			this.btnExit.HeightRequest = 50;
			this.btnExit.CanFocus = true;
			this.btnExit.Name = "btnExit";
			this.btnExit.UseUnderline = true;
			this.btnExit.BorderWidth = ((uint)(3));
			this.btnExit.Label = global::Mono.Unix.Catalog.GetString("Exit");
			this.vbox1.Add(this.btnExit);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.btnExit]));
			w8.Position = 5;
			w8.Expand = false;
			w8.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 260;
			this.DefaultHeight = 285;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.btnBack.Clicked += new global::System.EventHandler(this.OnBtnBackClicked);
			this.btnSettings.Clicked += new global::System.EventHandler(this.OnBtnSettingsClicked);
			this.btnSave.Clicked += new global::System.EventHandler(this.OnBtnSaveClicked);
			this.btnSaveExit.Clicked += new global::System.EventHandler(this.OnBtnSaveExitClicked);
			this.btnExit.Clicked += new global::System.EventHandler(this.OnBtnExitClicked);
		}
	}
}
