
// This file has been generated by the GUI designer. Do not modify.
namespace Mundus.Views.Windows
{
	public partial class SettingsWindow
	{
		private global::Gtk.Table tbUI;

		private global::Gtk.Button btnBack;

		private global::Gtk.Label lblBlank1;

		private global::Gtk.Label lblBlank2;

		private global::Gtk.Label lblBlank3;

		private global::Gtk.Label lblTitle;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Mundus.Views.Windows.SettingsWindow
			this.Name = "Mundus.Views.Windows.SettingsWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Settings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Mundus.Views.Windows.SettingsWindow.Gtk.Container+ContainerChild
			this.tbUI = new global::Gtk.Table(((uint)(3)), ((uint)(5)), false);
			this.tbUI.Name = "tbUI";
			this.tbUI.RowSpacing = ((uint)(3));
			this.tbUI.ColumnSpacing = ((uint)(3));
			// Container child tbUI.Gtk.Table+TableChild
			this.btnBack = new global::Gtk.Button();
			this.btnBack.WidthRequest = 50;
			this.btnBack.HeightRequest = 50;
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.BorderWidth = ((uint)(3));
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString("Back");
			this.tbUI.Add(this.btnBack);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tbUI[this.btnBack]));
			w1.XOptions = ((global::Gtk.AttachOptions)(0));
			w1.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank1 = new global::Gtk.Label();
			this.lblBlank1.WidthRequest = 40;
			this.lblBlank1.Name = "lblBlank1";
			this.tbUI.Add(this.lblBlank1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank1]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank2 = new global::Gtk.Label();
			this.lblBlank2.WidthRequest = 40;
			this.lblBlank2.Name = "lblBlank2";
			this.tbUI.Add(this.lblBlank2);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank2]));
			w3.LeftAttach = ((uint)(3));
			w3.RightAttach = ((uint)(4));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblBlank3 = new global::Gtk.Label();
			this.lblBlank3.WidthRequest = 40;
			this.lblBlank3.Name = "lblBlank3";
			this.tbUI.Add(this.lblBlank3);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblBlank3]));
			w4.LeftAttach = ((uint)(4));
			w4.RightAttach = ((uint)(5));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbUI.Gtk.Table+TableChild
			this.lblTitle = new global::Gtk.Label();
			this.lblTitle.Name = "lblTitle";
			this.lblTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Settings (replace with picture)");
			this.tbUI.Add(this.lblTitle);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tbUI[this.lblTitle]));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.tbUI);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 360;
			this.DefaultHeight = 300;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.btnBack.Clicked += new global::System.EventHandler(this.OnBtnBackClicked);
			this.btnBack.Activated += new global::System.EventHandler(this.OnBtnBackActivated);
		}
	}
}
